// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guideocelot.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	guideocelot.proto

It has these top-level messages:
	AllCredsWrapper
	CredWrapper
	VCSCreds
	RepoCredWrapper
	RepoCreds
	BuildQuery
	Builds
	BuildRuntimeInfo
	LogResponse
	RepoAccount
	Status
	Stage
	BuildSummary
	Summaries
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf3 "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllCredsWrapper struct {
	RepoCreds *RepoCredWrapper `protobuf:"bytes,1,opt,name=repoCreds" json:"repoCreds,omitempty"`
	VcsCreds  *CredWrapper     `protobuf:"bytes,3,opt,name=vcsCreds" json:"vcsCreds,omitempty"`
}

func (m *AllCredsWrapper) Reset()                    { *m = AllCredsWrapper{} }
func (m *AllCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*AllCredsWrapper) ProtoMessage()               {}
func (*AllCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllCredsWrapper) GetRepoCreds() *RepoCredWrapper {
	if m != nil {
		return m.RepoCreds
	}
	return nil
}

func (m *AllCredsWrapper) GetVcsCreds() *CredWrapper {
	if m != nil {
		return m.VcsCreds
	}
	return nil
}

type CredWrapper struct {
	Vcs []*VCSCreds `protobuf:"bytes,2,rep,name=vcs" json:"vcs,omitempty"`
}

func (m *CredWrapper) Reset()                    { *m = CredWrapper{} }
func (m *CredWrapper) String() string            { return proto.CompactTextString(m) }
func (*CredWrapper) ProtoMessage()               {}
func (*CredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CredWrapper) GetVcs() []*VCSCreds {
	if m != nil {
		return m.Vcs
	}
	return nil
}

type VCSCreds struct {
	ClientId     string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret" json:"clientSecret,omitempty"`
	TokenURL     string `protobuf:"bytes,3,opt,name=tokenURL" json:"tokenURL,omitempty"`
	AcctName     string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty"`
	Type         string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
}

func (m *VCSCreds) Reset()                    { *m = VCSCreds{} }
func (m *VCSCreds) String() string            { return proto.CompactTextString(m) }
func (*VCSCreds) ProtoMessage()               {}
func (*VCSCreds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VCSCreds) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VCSCreds) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *VCSCreds) GetTokenURL() string {
	if m != nil {
		return m.TokenURL
	}
	return ""
}

func (m *VCSCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *VCSCreds) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RepoCredWrapper struct {
	Repo []*RepoCreds `protobuf:"bytes,3,rep,name=repo" json:"repo,omitempty"`
}

func (m *RepoCredWrapper) Reset()                    { *m = RepoCredWrapper{} }
func (m *RepoCredWrapper) String() string            { return proto.CompactTextString(m) }
func (*RepoCredWrapper) ProtoMessage()               {}
func (*RepoCredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RepoCredWrapper) GetRepo() []*RepoCreds {
	if m != nil {
		return m.Repo
	}
	return nil
}

type RepoCreds struct {
	Username    string            `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password    string            `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RepoUrl     map[string]string `protobuf:"bytes,6,rep,name=repoUrl" json:"repoUrl,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AcctName    string            `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty"`
	Type        string            `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	ProjectName string            `protobuf:"bytes,7,opt,name=projectName" json:"projectName,omitempty"`
}

func (m *RepoCreds) Reset()                    { *m = RepoCreds{} }
func (m *RepoCreds) String() string            { return proto.CompactTextString(m) }
func (*RepoCreds) ProtoMessage()               {}
func (*RepoCreds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RepoCreds) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RepoCreds) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RepoCreds) GetRepoUrl() map[string]string {
	if m != nil {
		return m.RepoUrl
	}
	return nil
}

func (m *RepoCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *RepoCreds) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RepoCreds) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type BuildQuery struct {
	Hash    string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	BuildId int64  `protobuf:"varint,2,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildQuery) Reset()                    { *m = BuildQuery{} }
func (m *BuildQuery) String() string            { return proto.CompactTextString(m) }
func (*BuildQuery) ProtoMessage()               {}
func (*BuildQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BuildQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildQuery) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Builds struct {
	Builds map[string]*BuildRuntimeInfo `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Builds) Reset()                    { *m = Builds{} }
func (m *Builds) String() string            { return proto.CompactTextString(m) }
func (*Builds) ProtoMessage()               {}
func (*Builds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Builds) GetBuilds() map[string]*BuildRuntimeInfo {
	if m != nil {
		return m.Builds
	}
	return nil
}

type BuildRuntimeInfo struct {
	Done     bool   `protobuf:"varint,1,opt,name=done" json:"done,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	GrpcPort string `protobuf:"bytes,3,opt,name=grpcPort" json:"grpcPort,omitempty"`
	Hash     string `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	AcctName string `protobuf:"bytes,5,opt,name=acctName" json:"acctName,omitempty"`
	RepoName string `protobuf:"bytes,6,opt,name=repoName" json:"repoName,omitempty"`
}

func (m *BuildRuntimeInfo) Reset()                    { *m = BuildRuntimeInfo{} }
func (m *BuildRuntimeInfo) String() string            { return proto.CompactTextString(m) }
func (*BuildRuntimeInfo) ProtoMessage()               {}
func (*BuildRuntimeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BuildRuntimeInfo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *BuildRuntimeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BuildRuntimeInfo) GetGrpcPort() string {
	if m != nil {
		return m.GrpcPort
	}
	return ""
}

func (m *BuildRuntimeInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildRuntimeInfo) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

type LogResponse struct {
	OutputLine string `protobuf:"bytes,1,opt,name=outputLine" json:"outputLine,omitempty"`
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LogResponse) GetOutputLine() string {
	if m != nil {
		return m.OutputLine
	}
	return ""
}

type RepoAccount struct {
	Repo    string `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Limit   int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RepoAccount) Reset()                    { *m = RepoAccount{} }
func (m *RepoAccount) String() string            { return proto.CompactTextString(m) }
func (*RepoAccount) ProtoMessage()               {}
func (*RepoAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RepoAccount) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *RepoAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RepoAccount) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Status struct {
	BuildSum *BuildSummary `protobuf:"bytes,1,opt,name=buildSum" json:"buildSum,omitempty"`
	Stages   []*Stage      `protobuf:"bytes,2,rep,name=stages" json:"stages,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Status) GetBuildSum() *BuildSummary {
	if m != nil {
		return m.BuildSum
	}
	return nil
}

func (m *Status) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Stage         string                      `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Status        int32                       `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Messages      []string                    `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	StartTime     *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=startTime" json:"startTime,omitempty"`
	StageDuration float64                     `protobuf:"fixed64,6,opt,name=stageDuration" json:"stageDuration,omitempty"`
}

func (m *Stage) Reset()                    { *m = Stage{} }
func (m *Stage) String() string            { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()               {}
func (*Stage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Stage) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *Stage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Stage) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Stage) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Stage) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Stage) GetStageDuration() float64 {
	if m != nil {
		return m.StageDuration
	}
	return 0
}

type BuildSummary struct {
	Hash          string                      `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Failed        bool                        `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	BuildTime     *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=buildTime" json:"buildTime,omitempty"`
	Account       string                      `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	BuildDuration float64                     `protobuf:"fixed64,5,opt,name=buildDuration" json:"buildDuration,omitempty"`
	Repo          string                      `protobuf:"bytes,6,opt,name=repo" json:"repo,omitempty"`
	Branch        string                      `protobuf:"bytes,7,opt,name=branch" json:"branch,omitempty"`
	BuildId       int64                       `protobuf:"varint,8,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildSummary) Reset()                    { *m = BuildSummary{} }
func (m *BuildSummary) String() string            { return proto.CompactTextString(m) }
func (*BuildSummary) ProtoMessage()               {}
func (*BuildSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *BuildSummary) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildSummary) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *BuildSummary) GetBuildTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.BuildTime
	}
	return nil
}

func (m *BuildSummary) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BuildSummary) GetBuildDuration() float64 {
	if m != nil {
		return m.BuildDuration
	}
	return 0
}

func (m *BuildSummary) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *BuildSummary) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuildSummary) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Summaries struct {
	Sums []*BuildSummary `protobuf:"bytes,1,rep,name=sums" json:"sums,omitempty"`
}

func (m *Summaries) Reset()                    { *m = Summaries{} }
func (m *Summaries) String() string            { return proto.CompactTextString(m) }
func (*Summaries) ProtoMessage()               {}
func (*Summaries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Summaries) GetSums() []*BuildSummary {
	if m != nil {
		return m.Sums
	}
	return nil
}

func init() {
	proto.RegisterType((*AllCredsWrapper)(nil), "models.AllCredsWrapper")
	proto.RegisterType((*CredWrapper)(nil), "models.CredWrapper")
	proto.RegisterType((*VCSCreds)(nil), "models.VCSCreds")
	proto.RegisterType((*RepoCredWrapper)(nil), "models.RepoCredWrapper")
	proto.RegisterType((*RepoCreds)(nil), "models.RepoCreds")
	proto.RegisterType((*BuildQuery)(nil), "models.BuildQuery")
	proto.RegisterType((*Builds)(nil), "models.Builds")
	proto.RegisterType((*BuildRuntimeInfo)(nil), "models.BuildRuntimeInfo")
	proto.RegisterType((*LogResponse)(nil), "models.LogResponse")
	proto.RegisterType((*RepoAccount)(nil), "models.RepoAccount")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*Stage)(nil), "models.Stage")
	proto.RegisterType((*BuildSummary)(nil), "models.BuildSummary")
	proto.RegisterType((*Summaries)(nil), "models.Summaries")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GuideOcelot service

type GuideOcelotClient interface {
	GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error)
	SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error)
	SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error)
	CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error)
	Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error)
	LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error)
	StatusByPartialHash(ctx context.Context, in *google_protobuf3.StringValue, opts ...grpc.CallOption) (*Status, error)
}

type guideOcelotClient struct {
	cc *grpc.ClientConn
}

func NewGuideOcelotClient(cc *grpc.ClientConn) GuideOcelotClient {
	return &guideOcelotClient{cc}
}

func (c *guideOcelotClient) GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error) {
	out := new(CredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error) {
	out := new(RepoCredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error) {
	out := new(AllCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetAllCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/CheckConn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error) {
	out := new(Builds)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/BuildRuntime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[0], c.cc, "/models.GuideOcelot/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_LogsClient interface {
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type guideOcelotLogsClient struct {
	grpc.ClientStream
}

func (x *guideOcelotLogsClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error) {
	out := new(Summaries)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/LastFewSummaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) StatusByPartialHash(ctx context.Context, in *google_protobuf3.StringValue, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/StatusByPartialHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GuideOcelot service

type GuideOcelotServer interface {
	GetVCSCreds(context.Context, *google_protobuf.Empty) (*CredWrapper, error)
	SetVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	GetRepoCreds(context.Context, *google_protobuf.Empty) (*RepoCredWrapper, error)
	SetRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	GetAllCreds(context.Context, *google_protobuf.Empty) (*AllCredsWrapper, error)
	CheckConn(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	BuildRuntime(context.Context, *BuildQuery) (*Builds, error)
	Logs(*BuildQuery, GuideOcelot_LogsServer) error
	LastFewSummaries(context.Context, *RepoAccount) (*Summaries, error)
	StatusByPartialHash(context.Context, *google_protobuf3.StringValue) (*Status, error)
}

func RegisterGuideOcelotServer(s *grpc.Server, srv GuideOcelotServer) {
	s.RegisterService(&_GuideOcelot_serviceDesc, srv)
}

func _GuideOcelot_GetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetAllCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetAllCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_CheckConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).CheckConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/CheckConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).CheckConn(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/BuildRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, req.(*BuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).Logs(m, &guideOcelotLogsServer{stream})
}

type GuideOcelot_LogsServer interface {
	Send(*LogResponse) error
	grpc.ServerStream
}

type guideOcelotLogsServer struct {
	grpc.ServerStream
}

func (x *guideOcelotLogsServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_LastFewSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/LastFewSummaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_StatusByPartialHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf3.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).StatusByPartialHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/StatusByPartialHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).StatusByPartialHash(ctx, req.(*google_protobuf3.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuideOcelot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.GuideOcelot",
	HandlerType: (*GuideOcelotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVCSCreds",
			Handler:    _GuideOcelot_GetVCSCreds_Handler,
		},
		{
			MethodName: "SetVCSCreds",
			Handler:    _GuideOcelot_SetVCSCreds_Handler,
		},
		{
			MethodName: "GetRepoCreds",
			Handler:    _GuideOcelot_GetRepoCreds_Handler,
		},
		{
			MethodName: "SetRepoCreds",
			Handler:    _GuideOcelot_SetRepoCreds_Handler,
		},
		{
			MethodName: "GetAllCreds",
			Handler:    _GuideOcelot_GetAllCreds_Handler,
		},
		{
			MethodName: "CheckConn",
			Handler:    _GuideOcelot_CheckConn_Handler,
		},
		{
			MethodName: "BuildRuntime",
			Handler:    _GuideOcelot_BuildRuntime_Handler,
		},
		{
			MethodName: "LastFewSummaries",
			Handler:    _GuideOcelot_LastFewSummaries_Handler,
		},
		{
			MethodName: "StatusByPartialHash",
			Handler:    _GuideOcelot_StatusByPartialHash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _GuideOcelot_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "guideocelot.proto",
}

func init() { proto.RegisterFile("guideocelot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1061 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xfa, 0x67, 0x6b, 0x9f, 0x4d, 0xd3, 0x64, 0x12, 0x05, 0x6b, 0xa9, 0x42, 0x34, 0x6a,
	0xa5, 0x08, 0x09, 0xbb, 0x4d, 0xa9, 0x14, 0x05, 0x90, 0x48, 0x43, 0x08, 0x91, 0x52, 0x68, 0xd7,
	0x4d, 0xb9, 0x9e, 0xac, 0x27, 0xce, 0x92, 0xdd, 0x9d, 0xd5, 0xcc, 0x6c, 0x22, 0xdf, 0x72, 0xcb,
	0x15, 0x42, 0xe2, 0x0a, 0xf1, 0x3a, 0x3c, 0x00, 0xaf, 0xc0, 0x53, 0x70, 0x85, 0xe6, 0x6f, 0xbd,
	0x76, 0x62, 0x55, 0x5c, 0x79, 0xcf, 0xdf, 0xcc, 0x77, 0xbe, 0x73, 0xe6, 0x1c, 0xc3, 0xfa, 0xa4,
	0x4c, 0xc6, 0x94, 0xc5, 0x34, 0x65, 0x72, 0x50, 0x70, 0x26, 0x19, 0xf2, 0x33, 0x36, 0xa6, 0xa9,
	0x08, 0x3f, 0x9e, 0x30, 0x36, 0x49, 0xe9, 0x50, 0x6b, 0x2f, 0xca, 0xcb, 0x21, 0xcd, 0x0a, 0x39,
	0x35, 0x4e, 0xe1, 0x63, 0x6b, 0x24, 0x45, 0x32, 0x24, 0x79, 0xce, 0x24, 0x91, 0x09, 0xcb, 0x85,
	0xb5, 0x7e, 0xb2, 0x18, 0x2a, 0x93, 0x8c, 0x0a, 0x49, 0xb2, 0xc2, 0x3a, 0x6c, 0x2f, 0x3a, 0xdc,
	0x72, 0x52, 0x14, 0x94, 0xdb, 0x03, 0xf0, 0x14, 0x1e, 0x1d, 0xa6, 0xe9, 0x11, 0xa7, 0x63, 0xf1,
	0xa3, 0xb1, 0xa0, 0x97, 0xd0, 0xe3, 0xb4, 0x60, 0x5a, 0xd7, 0xf7, 0x76, 0xbc, 0xdd, 0x60, 0xef,
	0xa3, 0x81, 0x81, 0x3a, 0x88, 0xac, 0xc1, 0xfa, 0x46, 0x33, 0x4f, 0x34, 0x84, 0xee, 0x4d, 0x2c,
	0x4c, 0x54, 0x4b, 0x47, 0x6d, 0xb8, 0xa8, 0x7a, 0x44, 0xe5, 0x84, 0x9f, 0x43, 0x50, 0x33, 0x20,
	0x0c, 0xad, 0x9b, 0x58, 0xf4, 0x9b, 0x3b, 0xad, 0xdd, 0x60, 0x6f, 0xcd, 0x85, 0xbe, 0x3f, 0x1a,
	0x69, 0xef, 0x48, 0x19, 0xf1, 0xef, 0x1e, 0x74, 0x9d, 0x06, 0x85, 0xd0, 0x8d, 0xd3, 0x84, 0xe6,
	0xf2, 0x74, 0xac, 0x61, 0xf6, 0xa2, 0x4a, 0x46, 0x18, 0x56, 0xcc, 0xf7, 0x88, 0xc6, 0x9c, 0xca,
	0x7e, 0x53, 0xdb, 0xe7, 0x74, 0x2a, 0x5e, 0xb2, 0x6b, 0x9a, 0x9f, 0x47, 0x67, 0x1a, 0x70, 0x2f,
	0xaa, 0x64, 0x65, 0x23, 0x71, 0x2c, 0xbf, 0x27, 0x19, 0xed, 0xb7, 0x8d, 0xcd, 0xc9, 0x08, 0x41,
	0x5b, 0x4e, 0x0b, 0xda, 0xef, 0x68, 0xbd, 0xfe, 0xc6, 0xfb, 0xf0, 0x68, 0x81, 0x1a, 0xf4, 0x14,
	0xda, 0x8a, 0x9c, 0x7e, 0x4b, 0x27, 0xb4, 0xbe, 0xc8, 0xa0, 0x88, 0xb4, 0x19, 0xff, 0xd2, 0x84,
	0x5e, 0xa5, 0x53, 0xf7, 0x96, 0x82, 0xf2, 0x5c, 0xdd, 0x6b, 0x73, 0x72, 0xb2, 0xb2, 0x15, 0x44,
	0x88, 0x5b, 0xc6, 0xc7, 0x36, 0x9f, 0x4a, 0x46, 0xfb, 0xf0, 0x40, 0x9d, 0x76, 0xce, 0xd3, 0xbe,
	0xaf, 0xef, 0xdb, 0xbe, 0x73, 0x9f, 0xfe, 0x3a, 0xe7, 0xe9, 0x71, 0x2e, 0xf9, 0x34, 0x72, 0xee,
	0xff, 0x37, 0x53, 0xb4, 0x03, 0x41, 0xc1, 0xd9, 0x4f, 0xd4, 0x86, 0x3c, 0xd0, 0xa6, 0xba, 0x2a,
	0x3c, 0x80, 0x95, 0xfa, 0x55, 0x68, 0x0d, 0x5a, 0xd7, 0x74, 0x6a, 0xd3, 0x51, 0x9f, 0x68, 0x13,
	0x3a, 0x37, 0x24, 0x2d, 0xa9, 0x4d, 0xc3, 0x08, 0x07, 0xcd, 0x7d, 0x0f, 0x1f, 0x00, 0xbc, 0x2a,
	0x93, 0x74, 0xfc, 0xb6, 0xa4, 0x7c, 0xaa, 0xee, 0xbf, 0x22, 0xe2, 0xca, 0x86, 0xea, 0x6f, 0xd4,
	0x87, 0x07, 0x17, 0xca, 0xe3, 0xd4, 0x90, 0xd0, 0x8a, 0x9c, 0x88, 0x7f, 0xf5, 0xc0, 0xd7, 0xc1,
	0x02, 0xed, 0x81, 0xaf, 0xb5, 0xaa, 0x7f, 0x15, 0x1b, 0xa1, 0x63, 0xc3, 0xd8, 0xed, 0x8f, 0x61,
	0xc2, 0x7a, 0x86, 0x23, 0x08, 0x6a, 0xea, 0x7b, 0x50, 0x0f, 0xea, 0xa8, 0x83, 0xbd, 0xfe, 0xdc,
	0x99, 0x51, 0x99, 0xab, 0xa7, 0x77, 0x9a, 0x5f, 0xb2, 0x7a, 0x3e, 0x7f, 0x7a, 0xb0, 0xb6, 0x68,
	0x57, 0x69, 0x8d, 0x59, 0x6e, 0x0a, 0xdc, 0x8d, 0xf4, 0x37, 0x5a, 0x85, 0x66, 0x52, 0x58, 0x3e,
	0x9a, 0x49, 0xa1, 0xca, 0x32, 0xe1, 0x45, 0xfc, 0x86, 0x71, 0xe9, 0x9a, 0xd3, 0xc9, 0x15, 0x2d,
	0xed, 0x1a, 0x2d, 0xf5, 0x32, 0x76, 0x16, 0xca, 0x18, 0x42, 0x57, 0x55, 0x5b, 0xdb, 0x7c, 0x63,
	0x73, 0x32, 0xfe, 0x0c, 0x82, 0x33, 0x36, 0x89, 0xa8, 0x28, 0x58, 0x2e, 0x28, 0xda, 0x06, 0x60,
	0xa5, 0x2c, 0x4a, 0x79, 0x96, 0xe4, 0xae, 0x03, 0x6b, 0x1a, 0xfc, 0x16, 0x02, 0x55, 0xdb, 0xc3,
	0x38, 0x66, 0x65, 0xae, 0x91, 0xe8, 0x1e, 0xb7, 0x05, 0x52, 0xdf, 0xaa, 0x40, 0xc4, 0x98, 0x6d,
	0x3a, 0x4e, 0x54, 0x65, 0x4f, 0x93, 0x2c, 0x31, 0x09, 0x75, 0x22, 0x23, 0x60, 0x02, 0xfe, 0x48,
	0x12, 0x59, 0x0a, 0xf4, 0x0c, 0xba, 0xba, 0x16, 0xa3, 0x32, 0xb3, 0x73, 0x67, 0x73, 0x8e, 0xe3,
	0x51, 0x99, 0x65, 0x84, 0x4f, 0xa3, 0xca, 0x0b, 0x3d, 0x05, 0x5f, 0x48, 0x32, 0xa1, 0x6e, 0x6c,
	0x3c, 0x74, 0xfe, 0x23, 0xa5, 0x8d, 0xac, 0x11, 0xff, 0xe5, 0x41, 0x47, 0x6b, 0x14, 0x04, 0xad,
	0xb3, 0x88, 0x8d, 0xa0, 0xb4, 0x94, 0x73, 0xc6, 0x5d, 0x3f, 0x6a, 0x01, 0x6d, 0xe9, 0xc3, 0x65,
	0x29, 0x2c, 0x5e, 0x2b, 0x29, 0x3a, 0x33, 0x2a, 0x84, 0xbe, 0xb6, 0xbd, 0xd3, 0x52, 0x74, 0x3a,
	0x19, 0xed, 0x43, 0x4f, 0x48, 0xc2, 0xe5, 0xbb, 0xc4, 0xd6, 0x41, 0xf5, 0x9e, 0x19, 0xc1, 0x03,
	0x37, 0x82, 0x07, 0xef, 0xdc, 0x8c, 0x8e, 0x66, 0xce, 0xe8, 0x09, 0x3c, 0xd4, 0x60, 0xbe, 0x29,
	0xb9, 0x9e, 0xf0, 0xba, 0x52, 0x5e, 0x34, 0xaf, 0xc4, 0xff, 0x7a, 0xb0, 0x52, 0xe7, 0xe2, 0xde,
	0x27, 0xb2, 0x05, 0xfe, 0x25, 0x49, 0x52, 0x6a, 0x5e, 0x48, 0x37, 0xb2, 0x92, 0x02, 0xa7, 0x99,
	0xd3, 0xe0, 0x5a, 0x1f, 0x06, 0x57, 0x39, 0xd7, 0x6b, 0xda, 0x9e, 0xaf, 0xe9, 0x13, 0x78, 0xa8,
	0xdd, 0x2a, 0xd8, 0x1d, 0x03, 0x7b, 0x4e, 0x59, 0xf5, 0x89, 0x5f, 0xeb, 0x93, 0x2d, 0xf0, 0x2f,
	0x38, 0xc9, 0xe3, 0x2b, 0x3b, 0x43, 0xac, 0x54, 0x7f, 0xe0, 0xdd, 0xf9, 0x07, 0xfe, 0x12, 0x7a,
	0x26, 0xed, 0x84, 0x0a, 0xb4, 0x0b, 0x6d, 0x51, 0x66, 0xee, 0x81, 0xdf, 0xdf, 0x28, 0xda, 0x63,
	0xef, 0x8f, 0x0e, 0x04, 0x27, 0x6a, 0xf9, 0xfe, 0xa0, 0x97, 0x2f, 0x7a, 0x0d, 0xc1, 0x09, 0x95,
	0xd5, 0x1a, 0xd9, 0xba, 0x43, 0xc1, 0xb1, 0x5a, 0xbf, 0xe1, 0x7d, 0xdb, 0x0b, 0xaf, 0xff, 0xfc,
	0xf7, 0x3f, 0xbf, 0x35, 0x03, 0xd4, 0x1b, 0xde, 0x3c, 0x1f, 0xc6, 0x3a, 0xfe, 0x35, 0x04, 0xa3,
	0xda, 0x71, 0x77, 0x36, 0x57, 0xb8, 0xe4, 0x02, 0xbc, 0xa9, 0xcf, 0x5a, 0xc5, 0xb3, 0xb3, 0x0e,
	0xbc, 0x4f, 0xd1, 0x21, 0xac, 0x9c, 0x50, 0x39, 0xdb, 0x08, 0xcb, 0xe0, 0x2d, 0x5b, 0xc9, 0xb8,
	0x81, 0xbe, 0x80, 0x95, 0x51, 0xfd, 0x88, 0xbb, 0xbb, 0x67, 0x29, 0xa6, 0x06, 0xfa, 0x5a, 0xb3,
	0xe3, 0xfe, 0x13, 0x7c, 0xf8, 0xfa, 0x85, 0x7f, 0x0f, 0xb8, 0x81, 0xbe, 0x82, 0xde, 0xd1, 0x15,
	0x8d, 0xaf, 0x8f, 0x58, 0x9e, 0x2f, 0x8d, 0x5f, 0x0e, 0xe0, 0x73, 0xdb, 0xe1, 0x76, 0x62, 0x22,
	0x34, 0x57, 0x5a, 0xbd, 0x18, 0xc2, 0xd5, 0xf9, 0x79, 0x8e, 0x1b, 0xe8, 0x05, 0xb4, 0xcf, 0xd8,
	0x44, 0xdc, 0xeb, 0x5d, 0x55, 0xb2, 0x36, 0xe9, 0x70, 0xe3, 0x99, 0x87, 0xbe, 0x84, 0xb5, 0x33,
	0x22, 0xe4, 0xb7, 0xf4, 0x76, 0xd6, 0x57, 0x1b, 0x75, 0xb2, 0xec, 0x9c, 0x0b, 0x2b, 0x06, 0x2b,
	0x3f, 0xdc, 0x40, 0xc7, 0xb0, 0x61, 0x06, 0xd7, 0xab, 0xe9, 0x1b, 0xc2, 0x65, 0x42, 0xd2, 0xef,
	0xd4, 0xeb, 0x7b, 0x7c, 0x27, 0xb3, 0x91, 0xe4, 0x49, 0x3e, 0x79, 0xaf, 0x96, 0xc2, 0x0c, 0xb9,
	0x09, 0xc5, 0x8d, 0x0b, 0x5f, 0xfb, 0xbd, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xf5, 0x37,
	0xe1, 0x21, 0x0a, 0x00, 0x00,
}
