// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guideocelot.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	guideocelot.proto

It has these top-level messages:
	BuildReq
	AllCredsWrapper
	CredWrapper
	SSHKeyWrapper
	VCSCreds
	RepoCredWrapper
	RepoCreds
	StatusQuery
	BuildQuery
	Builds
	BuildRuntimeInfo
	LineResponse
	RepoAccount
	Status
	Stage
	BuildSummary
	Summaries
	PollRequest
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BuildReq struct {
	AcctRepo string `protobuf:"bytes,1,opt,name=acctRepo" json:"acctRepo,omitempty"`
	Hash     string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Branch   string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
}

func (m *BuildReq) Reset()                    { *m = BuildReq{} }
func (m *BuildReq) String() string            { return proto.CompactTextString(m) }
func (*BuildReq) ProtoMessage()               {}
func (*BuildReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BuildReq) GetAcctRepo() string {
	if m != nil {
		return m.AcctRepo
	}
	return ""
}

func (m *BuildReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildReq) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

type AllCredsWrapper struct {
	RepoCreds *RepoCredWrapper `protobuf:"bytes,1,opt,name=repoCreds" json:"repoCreds,omitempty"`
	VcsCreds  *CredWrapper     `protobuf:"bytes,3,opt,name=vcsCreds" json:"vcsCreds,omitempty"`
}

func (m *AllCredsWrapper) Reset()                    { *m = AllCredsWrapper{} }
func (m *AllCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*AllCredsWrapper) ProtoMessage()               {}
func (*AllCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllCredsWrapper) GetRepoCreds() *RepoCredWrapper {
	if m != nil {
		return m.RepoCreds
	}
	return nil
}

func (m *AllCredsWrapper) GetVcsCreds() *CredWrapper {
	if m != nil {
		return m.VcsCreds
	}
	return nil
}

type CredWrapper struct {
	Vcs []*VCSCreds `protobuf:"bytes,2,rep,name=vcs" json:"vcs,omitempty"`
}

func (m *CredWrapper) Reset()                    { *m = CredWrapper{} }
func (m *CredWrapper) String() string            { return proto.CompactTextString(m) }
func (*CredWrapper) ProtoMessage()               {}
func (*CredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CredWrapper) GetVcs() []*VCSCreds {
	if m != nil {
		return m.Vcs
	}
	return nil
}

type SSHKeyWrapper struct {
	AcctName   string `protobuf:"bytes,1,opt,name=acctName" json:"acctName,omitempty"`
	PrivateKey []byte `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Type       string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *SSHKeyWrapper) Reset()                    { *m = SSHKeyWrapper{} }
func (m *SSHKeyWrapper) String() string            { return proto.CompactTextString(m) }
func (*SSHKeyWrapper) ProtoMessage()               {}
func (*SSHKeyWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SSHKeyWrapper) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *SSHKeyWrapper) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SSHKeyWrapper) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type VCSCreds struct {
	ClientId     string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret" json:"clientSecret,omitempty"`
	TokenURL     string `protobuf:"bytes,3,opt,name=tokenURL" json:"tokenURL,omitempty"`
	AcctName     string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty"`
	Type         string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	SshFileLoc   string `protobuf:"bytes,6,opt,name=sshFileLoc" json:"sshFileLoc,omitempty"`
}

func (m *VCSCreds) Reset()                    { *m = VCSCreds{} }
func (m *VCSCreds) String() string            { return proto.CompactTextString(m) }
func (*VCSCreds) ProtoMessage()               {}
func (*VCSCreds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VCSCreds) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VCSCreds) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *VCSCreds) GetTokenURL() string {
	if m != nil {
		return m.TokenURL
	}
	return ""
}

func (m *VCSCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *VCSCreds) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VCSCreds) GetSshFileLoc() string {
	if m != nil {
		return m.SshFileLoc
	}
	return ""
}

type RepoCredWrapper struct {
	Repo []*RepoCreds `protobuf:"bytes,3,rep,name=repo" json:"repo,omitempty"`
}

func (m *RepoCredWrapper) Reset()                    { *m = RepoCredWrapper{} }
func (m *RepoCredWrapper) String() string            { return proto.CompactTextString(m) }
func (*RepoCredWrapper) ProtoMessage()               {}
func (*RepoCredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RepoCredWrapper) GetRepo() []*RepoCreds {
	if m != nil {
		return m.Repo
	}
	return nil
}

type RepoCreds struct {
	Username string            `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string            `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RepoUrl  map[string]string `protobuf:"bytes,6,rep,name=repoUrl" json:"repoUrl,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AcctName string            `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty"`
	// todo: should this be an enum?
	Type        string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	ProjectName string `protobuf:"bytes,7,opt,name=projectName" json:"projectName,omitempty"`
}

func (m *RepoCreds) Reset()                    { *m = RepoCreds{} }
func (m *RepoCreds) String() string            { return proto.CompactTextString(m) }
func (*RepoCreds) ProtoMessage()               {}
func (*RepoCreds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RepoCreds) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RepoCreds) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RepoCreds) GetRepoUrl() map[string]string {
	if m != nil {
		return m.RepoUrl
	}
	return nil
}

func (m *RepoCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *RepoCreds) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RepoCreds) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type StatusQuery struct {
	Hash        string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	AcctName    string `protobuf:"bytes,2,opt,name=acctName" json:"acctName,omitempty"`
	RepoName    string `protobuf:"bytes,3,opt,name=repoName" json:"repoName,omitempty"`
	PartialRepo string `protobuf:"bytes,4,opt,name=partialRepo" json:"partialRepo,omitempty"`
}

func (m *StatusQuery) Reset()                    { *m = StatusQuery{} }
func (m *StatusQuery) String() string            { return proto.CompactTextString(m) }
func (*StatusQuery) ProtoMessage()               {}
func (*StatusQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StatusQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *StatusQuery) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *StatusQuery) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *StatusQuery) GetPartialRepo() string {
	if m != nil {
		return m.PartialRepo
	}
	return ""
}

type BuildQuery struct {
	Hash    string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	BuildId int64  `protobuf:"varint,2,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildQuery) Reset()                    { *m = BuildQuery{} }
func (m *BuildQuery) String() string            { return proto.CompactTextString(m) }
func (*BuildQuery) ProtoMessage()               {}
func (*BuildQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BuildQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildQuery) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Builds struct {
	Builds map[string]*BuildRuntimeInfo `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Builds) Reset()                    { *m = Builds{} }
func (m *Builds) String() string            { return proto.CompactTextString(m) }
func (*Builds) ProtoMessage()               {}
func (*Builds) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Builds) GetBuilds() map[string]*BuildRuntimeInfo {
	if m != nil {
		return m.Builds
	}
	return nil
}

type BuildRuntimeInfo struct {
	Done     bool   `protobuf:"varint,1,opt,name=done" json:"done,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	GrpcPort string `protobuf:"bytes,3,opt,name=grpcPort" json:"grpcPort,omitempty"`
	Hash     string `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	AcctName string `protobuf:"bytes,5,opt,name=acctName" json:"acctName,omitempty"`
	RepoName string `protobuf:"bytes,6,opt,name=repoName" json:"repoName,omitempty"`
}

func (m *BuildRuntimeInfo) Reset()                    { *m = BuildRuntimeInfo{} }
func (m *BuildRuntimeInfo) String() string            { return proto.CompactTextString(m) }
func (*BuildRuntimeInfo) ProtoMessage()               {}
func (*BuildRuntimeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BuildRuntimeInfo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *BuildRuntimeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BuildRuntimeInfo) GetGrpcPort() string {
	if m != nil {
		return m.GrpcPort
	}
	return ""
}

func (m *BuildRuntimeInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildRuntimeInfo) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

type LineResponse struct {
	OutputLine string `protobuf:"bytes,1,opt,name=outputLine" json:"outputLine,omitempty"`
}

func (m *LineResponse) Reset()                    { *m = LineResponse{} }
func (m *LineResponse) String() string            { return proto.CompactTextString(m) }
func (*LineResponse) ProtoMessage()               {}
func (*LineResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *LineResponse) GetOutputLine() string {
	if m != nil {
		return m.OutputLine
	}
	return ""
}

type RepoAccount struct {
	Repo    string `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Limit   int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RepoAccount) Reset()                    { *m = RepoAccount{} }
func (m *RepoAccount) String() string            { return proto.CompactTextString(m) }
func (*RepoAccount) ProtoMessage()               {}
func (*RepoAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RepoAccount) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *RepoAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RepoAccount) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Status struct {
	BuildSum *BuildSummary `protobuf:"bytes,1,opt,name=buildSum" json:"buildSum,omitempty"`
	Stages   []*Stage      `protobuf:"bytes,2,rep,name=stages" json:"stages,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Status) GetBuildSum() *BuildSummary {
	if m != nil {
		return m.BuildSum
	}
	return nil
}

func (m *Status) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Stage         string                      `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Status        int32                       `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Messages      []string                    `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	StartTime     *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=startTime" json:"startTime,omitempty"`
	StageDuration float64                     `protobuf:"fixed64,6,opt,name=stageDuration" json:"stageDuration,omitempty"`
}

func (m *Stage) Reset()                    { *m = Stage{} }
func (m *Stage) String() string            { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()               {}
func (*Stage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Stage) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *Stage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Stage) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Stage) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Stage) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Stage) GetStageDuration() float64 {
	if m != nil {
		return m.StageDuration
	}
	return 0
}

type BuildSummary struct {
	Hash          string                      `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Failed        bool                        `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	BuildTime     *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=buildTime" json:"buildTime,omitempty"`
	Account       string                      `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	BuildDuration float64                     `protobuf:"fixed64,5,opt,name=buildDuration" json:"buildDuration,omitempty"`
	Repo          string                      `protobuf:"bytes,6,opt,name=repo" json:"repo,omitempty"`
	Branch        string                      `protobuf:"bytes,7,opt,name=branch" json:"branch,omitempty"`
	BuildId       int64                       `protobuf:"varint,8,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildSummary) Reset()                    { *m = BuildSummary{} }
func (m *BuildSummary) String() string            { return proto.CompactTextString(m) }
func (*BuildSummary) ProtoMessage()               {}
func (*BuildSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BuildSummary) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildSummary) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *BuildSummary) GetBuildTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.BuildTime
	}
	return nil
}

func (m *BuildSummary) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BuildSummary) GetBuildDuration() float64 {
	if m != nil {
		return m.BuildDuration
	}
	return 0
}

func (m *BuildSummary) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *BuildSummary) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuildSummary) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Summaries struct {
	Sums []*BuildSummary `protobuf:"bytes,1,rep,name=sums" json:"sums,omitempty"`
}

func (m *Summaries) Reset()                    { *m = Summaries{} }
func (m *Summaries) String() string            { return proto.CompactTextString(m) }
func (*Summaries) ProtoMessage()               {}
func (*Summaries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Summaries) GetSums() []*BuildSummary {
	if m != nil {
		return m.Sums
	}
	return nil
}

type PollRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Repo     string `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	IsUpdate bool   `protobuf:"varint,3,opt,name=isUpdate" json:"isUpdate,omitempty"`
	Cron     string `protobuf:"bytes,4,opt,name=cron" json:"cron,omitempty"`
	Branches string `protobuf:"bytes,5,opt,name=branches" json:"branches,omitempty"`
}

func (m *PollRequest) Reset()                    { *m = PollRequest{} }
func (m *PollRequest) String() string            { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()               {}
func (*PollRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PollRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PollRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *PollRequest) GetIsUpdate() bool {
	if m != nil {
		return m.IsUpdate
	}
	return false
}

func (m *PollRequest) GetCron() string {
	if m != nil {
		return m.Cron
	}
	return ""
}

func (m *PollRequest) GetBranches() string {
	if m != nil {
		return m.Branches
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildReq)(nil), "models.BuildReq")
	proto.RegisterType((*AllCredsWrapper)(nil), "models.AllCredsWrapper")
	proto.RegisterType((*CredWrapper)(nil), "models.CredWrapper")
	proto.RegisterType((*SSHKeyWrapper)(nil), "models.SSHKeyWrapper")
	proto.RegisterType((*VCSCreds)(nil), "models.VCSCreds")
	proto.RegisterType((*RepoCredWrapper)(nil), "models.RepoCredWrapper")
	proto.RegisterType((*RepoCreds)(nil), "models.RepoCreds")
	proto.RegisterType((*StatusQuery)(nil), "models.StatusQuery")
	proto.RegisterType((*BuildQuery)(nil), "models.BuildQuery")
	proto.RegisterType((*Builds)(nil), "models.Builds")
	proto.RegisterType((*BuildRuntimeInfo)(nil), "models.BuildRuntimeInfo")
	proto.RegisterType((*LineResponse)(nil), "models.LineResponse")
	proto.RegisterType((*RepoAccount)(nil), "models.RepoAccount")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*Stage)(nil), "models.Stage")
	proto.RegisterType((*BuildSummary)(nil), "models.BuildSummary")
	proto.RegisterType((*Summaries)(nil), "models.Summaries")
	proto.RegisterType((*PollRequest)(nil), "models.PollRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GuideOcelot service

type GuideOcelotClient interface {
	GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error)
	SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error)
	SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error)
	BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error)
	Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error)
	LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error)
	GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error)
	WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error)
	PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type guideOcelotClient struct {
	cc *grpc.ClientConn
}

func NewGuideOcelotClient(cc *grpc.ClientConn) GuideOcelotClient {
	return &guideOcelotClient{cc}
}

func (c *guideOcelotClient) GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error) {
	out := new(CredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/CheckConn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSPrivateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error) {
	out := new(RepoCredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error) {
	out := new(AllCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetAllCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error) {
	out := new(Builds)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/BuildRuntime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[0], c.cc, "/models.GuideOcelot/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_LogsClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotLogsClient struct {
	grpc.ClientStream
}

func (x *guideOcelotLogsClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error) {
	out := new(Summaries)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/LastFewSummaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/WatchRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[1], c.cc, "/models.GuideOcelot/BuildRepoAndHash", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotBuildRepoAndHashClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_BuildRepoAndHashClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotBuildRepoAndHashClient struct {
	grpc.ClientStream
}

func (x *guideOcelotBuildRepoAndHashClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/PollRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GuideOcelot service

type GuideOcelotServer interface {
	GetVCSCreds(context.Context, *google_protobuf.Empty) (*CredWrapper, error)
	SetVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	CheckConn(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(context.Context, *SSHKeyWrapper) (*google_protobuf.Empty, error)
	GetRepoCreds(context.Context, *google_protobuf.Empty) (*RepoCredWrapper, error)
	SetRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	GetAllCreds(context.Context, *google_protobuf.Empty) (*AllCredsWrapper, error)
	BuildRuntime(context.Context, *BuildQuery) (*Builds, error)
	Logs(*BuildQuery, GuideOcelot_LogsServer) error
	LastFewSummaries(context.Context, *RepoAccount) (*Summaries, error)
	GetStatus(context.Context, *StatusQuery) (*Status, error)
	WatchRepo(context.Context, *RepoAccount) (*google_protobuf.Empty, error)
	BuildRepoAndHash(*BuildReq, GuideOcelot_BuildRepoAndHashServer) error
	PollRepo(context.Context, *PollRequest) (*google_protobuf.Empty, error)
}

func RegisterGuideOcelotServer(s *grpc.Server, srv GuideOcelotServer) {
	s.RegisterService(&_GuideOcelot_serviceDesc, srv)
}

func _GuideOcelot_GetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_CheckConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).CheckConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/CheckConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).CheckConn(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetAllCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetAllCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/BuildRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, req.(*BuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).Logs(m, &guideOcelotLogsServer{stream})
}

type GuideOcelot_LogsServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotLogsServer struct {
	grpc.ServerStream
}

func (x *guideOcelotLogsServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_LastFewSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/LastFewSummaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetStatus(ctx, req.(*StatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_WatchRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).WatchRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/WatchRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).WatchRepo(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRepoAndHash_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).BuildRepoAndHash(m, &guideOcelotBuildRepoAndHashServer{stream})
}

type GuideOcelot_BuildRepoAndHashServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotBuildRepoAndHashServer struct {
	grpc.ServerStream
}

func (x *guideOcelotBuildRepoAndHashServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_PollRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).PollRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/PollRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).PollRepo(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuideOcelot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.GuideOcelot",
	HandlerType: (*GuideOcelotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVCSCreds",
			Handler:    _GuideOcelot_GetVCSCreds_Handler,
		},
		{
			MethodName: "SetVCSCreds",
			Handler:    _GuideOcelot_SetVCSCreds_Handler,
		},
		{
			MethodName: "CheckConn",
			Handler:    _GuideOcelot_CheckConn_Handler,
		},
		{
			MethodName: "SetVCSPrivateKey",
			Handler:    _GuideOcelot_SetVCSPrivateKey_Handler,
		},
		{
			MethodName: "GetRepoCreds",
			Handler:    _GuideOcelot_GetRepoCreds_Handler,
		},
		{
			MethodName: "SetRepoCreds",
			Handler:    _GuideOcelot_SetRepoCreds_Handler,
		},
		{
			MethodName: "GetAllCreds",
			Handler:    _GuideOcelot_GetAllCreds_Handler,
		},
		{
			MethodName: "BuildRuntime",
			Handler:    _GuideOcelot_BuildRuntime_Handler,
		},
		{
			MethodName: "LastFewSummaries",
			Handler:    _GuideOcelot_LastFewSummaries_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GuideOcelot_GetStatus_Handler,
		},
		{
			MethodName: "WatchRepo",
			Handler:    _GuideOcelot_WatchRepo_Handler,
		},
		{
			MethodName: "PollRepo",
			Handler:    _GuideOcelot_PollRepo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _GuideOcelot_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildRepoAndHash",
			Handler:       _GuideOcelot_BuildRepoAndHash_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "guideocelot.proto",
}

func init() { proto.RegisterFile("guideocelot.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xf6, 0xec, 0xae, 0xd7, 0xb3, 0x35, 0xeb, 0xc4, 0xe9, 0x84, 0xb0, 0x1a, 0x50, 0xb0, 0x5a,
	0x89, 0x14, 0x71, 0x58, 0x27, 0x86, 0x48, 0xc6, 0xfc, 0x88, 0x60, 0x12, 0x27, 0x8a, 0x03, 0xc9,
	0x6c, 0x4c, 0x8e, 0xa8, 0x3d, 0xdb, 0xb1, 0x87, 0xcc, 0x4e, 0x8f, 0xbb, 0x7b, 0x1c, 0xad, 0xb8,
	0x71, 0x80, 0x03, 0x27, 0xc4, 0x9d, 0xc7, 0xe0, 0x15, 0x78, 0x00, 0x5e, 0x81, 0xa7, 0xe0, 0x84,
	0xfa, 0x6f, 0xb6, 0x67, 0xbd, 0xeb, 0x88, 0xd3, 0x4c, 0xfd, 0x75, 0x7d, 0x55, 0xd5, 0xd5, 0x55,
	0x70, 0xe5, 0xb8, 0xca, 0xc6, 0x94, 0xa5, 0x34, 0x67, 0x72, 0x58, 0x72, 0x26, 0x19, 0xea, 0x4e,
	0xd8, 0x98, 0xe6, 0x22, 0x7e, 0xef, 0x98, 0xb1, 0xe3, 0x9c, 0x6e, 0x69, 0xee, 0x51, 0xf5, 0x6a,
	0x8b, 0x4e, 0x4a, 0x39, 0x35, 0x4a, 0xf1, 0xfb, 0x56, 0x48, 0xca, 0x6c, 0x8b, 0x14, 0x05, 0x93,
	0x44, 0x66, 0xac, 0x10, 0x56, 0xfa, 0xc1, 0xbc, 0xa9, 0xcc, 0x26, 0x54, 0x48, 0x32, 0x29, 0x8d,
	0x02, 0x4e, 0x20, 0xfc, 0xaa, 0xca, 0xf2, 0x71, 0x42, 0x4f, 0x51, 0x0c, 0x21, 0x49, 0x53, 0x99,
	0xd0, 0x92, 0x0d, 0x82, 0xcd, 0xe0, 0x76, 0x2f, 0xa9, 0x69, 0x84, 0xa0, 0x73, 0x42, 0xc4, 0xc9,
	0xa0, 0xa5, 0xf9, 0xfa, 0x1f, 0x5d, 0x87, 0xee, 0x11, 0x27, 0x45, 0x7a, 0x32, 0x68, 0x6b, 0xae,
	0xa5, 0xf0, 0x14, 0x2e, 0xdf, 0xcf, 0xf3, 0x3d, 0x4e, 0xc7, 0xe2, 0x25, 0x27, 0x65, 0x49, 0x39,
	0xba, 0x07, 0x3d, 0x4e, 0x4b, 0xa6, 0x79, 0xfa, 0xec, 0x68, 0xfb, 0xdd, 0xa1, 0x09, 0x6f, 0x98,
	0x58, 0x81, 0xd5, 0x4d, 0x66, 0x9a, 0x68, 0x0b, 0xc2, 0xb3, 0x54, 0x18, 0xab, 0xb6, 0xb6, 0xba,
	0xea, 0xac, 0x7c, 0x8b, 0x5a, 0x09, 0xdf, 0x85, 0xc8, 0x13, 0x20, 0x0c, 0xed, 0xb3, 0x54, 0x0c,
	0x5a, 0x9b, 0xed, 0xdb, 0xd1, 0xf6, 0x86, 0x33, 0xfd, 0x6e, 0x6f, 0xa4, 0xb5, 0x13, 0x25, 0xc4,
	0xdf, 0xc3, 0xfa, 0x68, 0xf4, 0xe8, 0x09, 0x9d, 0x3a, 0x23, 0x9b, 0x86, 0x6f, 0xc8, 0x84, 0xfa,
	0x69, 0x50, 0x34, 0xba, 0x01, 0x50, 0xf2, 0xec, 0x8c, 0x48, 0xfa, 0x84, 0x4e, 0x75, 0x32, 0xfa,
	0x89, 0xc7, 0x51, 0x69, 0x92, 0xd3, 0x92, 0xda, 0x84, 0xe8, 0x7f, 0xfc, 0x67, 0x00, 0xa1, 0x73,
	0xa9, 0x0e, 0x4f, 0xf3, 0x8c, 0x16, 0xf2, 0xf1, 0xd8, 0x1d, 0xee, 0x68, 0x84, 0xa1, 0x6f, 0xfe,
	0x47, 0x34, 0xe5, 0x54, 0xda, 0x5c, 0x37, 0x78, 0xca, 0x5e, 0xb2, 0xd7, 0xb4, 0x38, 0x4c, 0x0e,
	0xac, 0x93, 0x9a, 0x6e, 0x00, 0xef, 0xcc, 0x01, 0x77, 0xc0, 0x56, 0x67, 0xc0, 0x54, 0x30, 0x42,
	0x9c, 0x3c, 0xcc, 0x72, 0x7a, 0xc0, 0xd2, 0x41, 0x57, 0x4b, 0x3c, 0x0e, 0xde, 0x81, 0xcb, 0x73,
	0xb5, 0x41, 0xb7, 0xa0, 0xa3, 0xaa, 0x33, 0x68, 0xeb, 0x8c, 0x5e, 0x99, 0x2f, 0xa1, 0x48, 0xb4,
	0x18, 0xff, 0xda, 0x82, 0x5e, 0xcd, 0x53, 0xb8, 0x2a, 0x41, 0x79, 0xe1, 0x25, 0xd4, 0xd1, 0x4a,
	0x56, 0x12, 0x21, 0xde, 0x30, 0x3e, 0xb6, 0xf1, 0xd6, 0x34, 0xda, 0x81, 0x35, 0x75, 0xda, 0x21,
	0xcf, 0x07, 0x5d, 0xed, 0xef, 0xc6, 0x39, 0x7f, 0xfa, 0xef, 0x90, 0xe7, 0x0f, 0x0a, 0xc9, 0xa7,
	0x89, 0x53, 0xff, 0xdf, 0x99, 0xd8, 0x84, 0xa8, 0xe4, 0xec, 0x07, 0x6a, 0x4d, 0xd6, 0xb4, 0xc8,
	0x67, 0xc5, 0xbb, 0xd0, 0xf7, 0x5d, 0xa1, 0x0d, 0x68, 0xbf, 0xa6, 0x53, 0x1b, 0x8e, 0xfa, 0x45,
	0xd7, 0x60, 0xf5, 0x8c, 0xe4, 0x15, 0xb5, 0x61, 0x18, 0x62, 0xb7, 0xb5, 0x13, 0xe0, 0x1f, 0x21,
	0x1a, 0x49, 0x22, 0x2b, 0xf1, 0xbc, 0xa2, 0x7c, 0x5a, 0xb7, 0x52, 0xe0, 0xb5, 0x92, 0x0f, 0xb8,
	0x35, 0x07, 0x38, 0x86, 0x50, 0xc5, 0xa5, 0x65, 0xb6, 0xe4, 0x8e, 0xd6, 0xc0, 0x09, 0x97, 0x19,
	0xc9, 0x75, 0xd7, 0x76, 0x2c, 0xf0, 0x19, 0x0b, 0xef, 0x02, 0xe8, 0x06, 0x5f, 0xee, 0x7b, 0x00,
	0x6b, 0x47, 0x4a, 0xe3, 0xb1, 0xa9, 0x40, 0x3b, 0x71, 0x24, 0xfe, 0x2d, 0x80, 0xae, 0x36, 0x16,
	0x68, 0x1b, 0xba, 0x9a, 0xab, 0xba, 0x57, 0x95, 0x22, 0x76, 0xa5, 0x30, 0x72, 0xfb, 0x31, 0x65,
	0xb0, 0x9a, 0xf1, 0x08, 0x22, 0x8f, 0xbd, 0x20, 0x65, 0x43, 0x3f, 0x65, 0xd1, 0xf6, 0xa0, 0x71,
	0x66, 0x52, 0x15, 0xea, 0xb1, 0x7a, 0x5c, 0xbc, 0x62, 0x7e, 0x32, 0xff, 0x08, 0x60, 0x63, 0x5e,
	0xae, 0xc2, 0x1a, 0xb3, 0xc2, 0xdc, 0xae, 0x30, 0xd1, 0xff, 0xe8, 0x12, 0xb4, 0xb2, 0xd2, 0x26,
	0xb3, 0x95, 0x95, 0x2a, 0x8d, 0xc7, 0xbc, 0x4c, 0x9f, 0x31, 0x2e, 0x5d, 0x1a, 0x1d, 0x5d, 0xa7,
	0xa5, 0xb3, 0xa4, 0x24, 0xab, 0x17, 0x94, 0xa4, 0xdb, 0x2c, 0x09, 0x1e, 0x42, 0xff, 0x20, 0x2b,
	0x68, 0x42, 0x45, 0xc9, 0x0a, 0xa1, 0xbb, 0x8c, 0x55, 0xb2, 0xac, 0xa4, 0xe2, 0xda, 0xe8, 0x3d,
	0x0e, 0x7e, 0x0e, 0x91, 0x2a, 0xd4, 0xfd, 0x34, 0x65, 0x55, 0xa1, 0xa1, 0xf0, 0xd9, 0x03, 0xac,
	0xff, 0x55, 0x85, 0x88, 0x11, 0xdb, 0x78, 0x1c, 0xa9, 0x2e, 0x5d, 0x9e, 0x4d, 0x32, 0x13, 0xd1,
	0x6a, 0x62, 0x08, 0x4c, 0xa0, 0x6b, 0x2e, 0x1c, 0xba, 0x03, 0xa1, 0x2e, 0xc6, 0xa8, 0x9a, 0xd8,
	0x67, 0xf7, 0x5a, 0x23, 0xc9, 0xa3, 0x6a, 0x32, 0x21, 0x7c, 0x9a, 0xd4, 0x5a, 0xe8, 0x16, 0x74,
	0x85, 0x24, 0xc7, 0xd4, 0xbd, 0x9a, 0xeb, 0x4e, 0x7f, 0xa4, 0xb8, 0x89, 0x15, 0xe2, 0xbf, 0x02,
	0x58, 0xd5, 0x1c, 0x05, 0x41, 0xf3, 0x2c, 0x62, 0x43, 0x28, 0x2e, 0xe5, 0x9c, 0x71, 0xd7, 0x0d,
	0x9a, 0x50, 0x13, 0x43, 0x68, 0x60, 0x16, 0xaf, 0xa5, 0x54, 0x3e, 0x27, 0x54, 0x08, 0xed, 0xb6,
	0xb3, 0xd9, 0x56, 0xf9, 0x74, 0x34, 0xda, 0x81, 0x9e, 0x90, 0x84, 0xcb, 0x17, 0x99, 0x2d, 0x84,
	0xba, 0x7c, 0x66, 0xac, 0x0d, 0xdd, 0x58, 0x1b, 0xbe, 0x70, 0x63, 0x2d, 0x99, 0x29, 0xa3, 0x9b,
	0xb0, 0xae, 0xc1, 0x7c, 0x5d, 0x71, 0x3d, 0x14, 0x75, 0xa9, 0x82, 0xa4, 0xc9, 0xc4, 0xff, 0x06,
	0xd0, 0xf7, 0x73, 0xb1, 0xb0, 0x47, 0xae, 0x43, 0xf7, 0x15, 0xc9, 0x72, 0x6a, 0x5a, 0x24, 0x4c,
	0x2c, 0xa5, 0xc0, 0xe9, 0xcc, 0x69, 0x70, 0xed, 0xb7, 0x83, 0xab, 0x95, 0xfd, 0x9a, 0x76, 0x9a,
	0x35, 0xbd, 0x09, 0xeb, 0x5a, 0xad, 0x86, 0xbd, 0x6a, 0x60, 0x37, 0x98, 0xf5, 0x3d, 0xe9, 0x7a,
	0xf7, 0x64, 0x36, 0x90, 0xd7, 0xfc, 0x81, 0xec, 0x77, 0x78, 0xd8, 0xec, 0xf0, 0x7b, 0xd0, 0x33,
	0x61, 0x67, 0x54, 0xa0, 0xdb, 0xd0, 0x11, 0xd5, 0xc4, 0x75, 0xf8, 0xe2, 0x8b, 0xa2, 0x35, 0xf0,
	0x2f, 0x01, 0x44, 0xcf, 0x58, 0x9e, 0x27, 0xf4, 0xb4, 0xa2, 0x42, 0xfa, 0xc1, 0x04, 0xcd, 0x60,
	0x1c, 0xcc, 0x96, 0x07, 0x33, 0x86, 0x30, 0x13, 0x87, 0xe5, 0x98, 0x48, 0x93, 0xb3, 0x30, 0xa9,
	0x69, 0xa5, 0x9f, 0x72, 0x56, 0xb8, 0x4e, 0x54, 0xff, 0x4a, 0xdf, 0x04, 0x42, 0x85, 0xeb, 0x44,
	0x47, 0x6f, 0xff, 0xbc, 0x06, 0xd1, 0xbe, 0xda, 0x9c, 0xbe, 0xd5, 0x9b, 0x13, 0x7a, 0x0a, 0xd1,
	0x3e, 0x95, 0xf5, 0xb8, 0xbd, 0x7e, 0xae, 0x18, 0x0f, 0xd4, 0xee, 0x14, 0x2f, 0x5a, 0x23, 0xf0,
	0x95, 0x9f, 0xfe, 0xfe, 0xe7, 0xf7, 0x56, 0x84, 0x7a, 0x5b, 0x67, 0x77, 0xb7, 0x52, 0x6d, 0xff,
	0x14, 0xa2, 0x91, 0x77, 0xdc, 0xb9, 0x15, 0x22, 0x5e, 0xe2, 0x00, 0x5f, 0xd3, 0x67, 0x5d, 0xc2,
	0xb3, 0xb3, 0x76, 0x83, 0x0f, 0xd1, 0xe7, 0xd0, 0xdb, 0x3b, 0xa1, 0xe9, 0xeb, 0x3d, 0x56, 0x14,
	0x4b, 0xb1, 0x2d, 0x3b, 0x72, 0x05, 0xed, 0xc1, 0x86, 0x41, 0xf3, 0x6c, 0xb6, 0x71, 0xbc, 0x53,
	0xf7, 0xa7, 0xbf, 0xc4, 0x5c, 0x70, 0xc8, 0x7d, 0xe8, 0xef, 0x53, 0x39, 0x9b, 0xce, 0xcb, 0x60,
	0x2c, 0xdb, 0xcf, 0xf0, 0x0a, 0xfa, 0x14, 0xfa, 0x23, 0xff, 0x88, 0xf3, 0x7b, 0xc0, 0x05, 0xfe,
	0xbf, 0xd4, 0x15, 0x72, 0x0b, 0xe2, 0xdb, 0xdd, 0xcf, 0xad, 0x92, 0x78, 0x05, 0x7d, 0x6c, 0x1b,
	0xd6, 0x4e, 0x00, 0x84, 0x1a, 0x37, 0x55, 0x0f, 0xba, 0xf8, 0x52, 0x73, 0x3e, 0x69, 0xab, 0xce,
	0x01, 0x3b, 0x16, 0x0b, 0xb5, 0xeb, 0xbb, 0xee, 0xbf, 0xdc, 0x78, 0xe5, 0x4e, 0x80, 0x3e, 0x83,
	0x8d, 0x03, 0x22, 0xe4, 0x43, 0xfa, 0x66, 0xd6, 0x27, 0x57, 0xfd, 0x70, 0xed, 0xbb, 0x1d, 0xd7,
	0x39, 0xa8, 0xf5, 0xf0, 0x0a, 0xda, 0x86, 0xde, 0x3e, 0x95, 0xf6, 0x2d, 0xbe, 0xea, 0xbd, 0xa4,
	0x6e, 0x19, 0x98, 0xe1, 0x34, 0x4c, 0xbc, 0x82, 0x76, 0xa1, 0xf7, 0x92, 0xc8, 0xf4, 0x44, 0xaf,
	0xdd, 0x0b, 0x5d, 0x2d, 0xcf, 0xed, 0x17, 0x6e, 0x36, 0x2a, 0xed, 0x62, 0xfc, 0x48, 0x3d, 0x5d,
	0x1b, 0xcd, 0xa9, 0x4a, 0x4f, 0x2f, 0x88, 0xf6, 0x13, 0x08, 0x4d, 0x5b, 0xfb, 0xae, 0xbd, 0x46,
	0x5f, 0xee, 0xfa, 0xa8, 0xab, 0x39, 0x1f, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x1f, 0x8c,
	0xf9, 0xc8, 0x0c, 0x00, 0x00,
}
