// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	build.proto
	common.proto
	commonevententities.proto
	projectrootdir.proto
	respositories.proto
	webhook.proto

It has these top-level messages:
	BuildConfig
	Stage
	Result
	WerkerTask
	PushBuildBundle
	PRBuildBundle
	LinkUrl
	LinkAndName
	Links
	Owner
	Repository
	PullRequestEntity
	PRInfo
	Project
	Changeset
	Commit
	RepoSourceFile
	PaginatedRootDirs
	PaginatedRepository
	RepoPush
	PullRequest
	PullRequestApproved
	CreateWebhook
	GetWebhooks
	Webhooks
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StageResultVal int32

const (
	StageResultVal_PASS StageResultVal = 0
	StageResultVal_FAIL StageResultVal = 1
)

var StageResultVal_name = map[int32]string{
	0: "PASS",
	1: "FAIL",
}
var StageResultVal_value = map[string]int32{
	"PASS": 0,
	"FAIL": 1,
}

func (x StageResultVal) String() string {
	return proto.EnumName(StageResultVal_name, int32(x))
}
func (StageResultVal) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// this is a direct translation of the ocelot.yaml file
type BuildConfig struct {
	Image string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	// @inject_tag: yaml:"buildTool"
	BuildTool string   `protobuf:"bytes,2,opt,name=buildTool" json:"buildTool,omitempty" yaml:"buildTool"`
	Packages  []string `protobuf:"bytes,3,rep,name=packages" json:"packages,omitempty"`
	Branches  []string `protobuf:"bytes,4,rep,name=branches" json:"branches,omitempty"`
	Env       []string `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Stages    []*Stage `protobuf:"bytes,7,rep,name=stages" json:"stages,omitempty"`
}

func (m *BuildConfig) Reset()                    { *m = BuildConfig{} }
func (m *BuildConfig) String() string            { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()               {}
func (*BuildConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BuildConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BuildConfig) GetBuildTool() string {
	if m != nil {
		return m.BuildTool
	}
	return ""
}

func (m *BuildConfig) GetPackages() []string {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *BuildConfig) GetBranches() []string {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *BuildConfig) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *BuildConfig) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

type Stage struct {
	Env    []string `protobuf:"bytes,1,rep,name=env" json:"env,omitempty"`
	Script []string `protobuf:"bytes,2,rep,name=script" json:"script,omitempty"`
	Name   string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *Stage) Reset()                    { *m = Stage{} }
func (m *Stage) String() string            { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()               {}
func (*Stage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Stage) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Stage) GetScript() []string {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Stage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Result struct {
	Stage    string         `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	Status   StageResultVal `protobuf:"varint,2,opt,name=status,enum=protos.StageResultVal" json:"status,omitempty"`
	Error    string         `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Messages []string       `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *Result) GetStatus() StageResultVal {
	if m != nil {
		return m.Status
	}
	return StageResultVal_PASS
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type WerkerTask struct {
	VaultToken   string       `protobuf:"bytes,1,opt,name=vaultToken" json:"vaultToken,omitempty"`
	CheckoutHash string       `protobuf:"bytes,2,opt,name=checkoutHash" json:"checkoutHash,omitempty"`
	BuildConf    *BuildConfig `protobuf:"bytes,3,opt,name=buildConf" json:"buildConf,omitempty"`
	VcsToken     string       `protobuf:"bytes,4,opt,name=vcsToken" json:"vcsToken,omitempty"`
	VcsType      string       `protobuf:"bytes,5,opt,name=vcsType" json:"vcsType,omitempty"`
	FullName     string       `protobuf:"bytes,6,opt,name=fullName" json:"fullName,omitempty"`
	Id           int64        `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
}

func (m *WerkerTask) Reset()                    { *m = WerkerTask{} }
func (m *WerkerTask) String() string            { return proto.CompactTextString(m) }
func (*WerkerTask) ProtoMessage()               {}
func (*WerkerTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *WerkerTask) GetVaultToken() string {
	if m != nil {
		return m.VaultToken
	}
	return ""
}

func (m *WerkerTask) GetCheckoutHash() string {
	if m != nil {
		return m.CheckoutHash
	}
	return ""
}

func (m *WerkerTask) GetBuildConf() *BuildConfig {
	if m != nil {
		return m.BuildConf
	}
	return nil
}

func (m *WerkerTask) GetVcsToken() string {
	if m != nil {
		return m.VcsToken
	}
	return ""
}

func (m *WerkerTask) GetVcsType() string {
	if m != nil {
		return m.VcsType
	}
	return ""
}

func (m *WerkerTask) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *WerkerTask) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PushBuildBundle struct {
	Config       *BuildConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	PushData     *RepoPush    `protobuf:"bytes,2,opt,name=pushData" json:"pushData,omitempty"`
	VaultToken   string       `protobuf:"bytes,3,opt,name=vaultToken" json:"vaultToken,omitempty"`
	CheckoutHash string       `protobuf:"bytes,4,opt,name=checkoutHash" json:"checkoutHash,omitempty"`
}

func (m *PushBuildBundle) Reset()                    { *m = PushBuildBundle{} }
func (m *PushBuildBundle) String() string            { return proto.CompactTextString(m) }
func (*PushBuildBundle) ProtoMessage()               {}
func (*PushBuildBundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PushBuildBundle) GetConfig() *BuildConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *PushBuildBundle) GetPushData() *RepoPush {
	if m != nil {
		return m.PushData
	}
	return nil
}

func (m *PushBuildBundle) GetVaultToken() string {
	if m != nil {
		return m.VaultToken
	}
	return ""
}

func (m *PushBuildBundle) GetCheckoutHash() string {
	if m != nil {
		return m.CheckoutHash
	}
	return ""
}

type PRBuildBundle struct {
	Config       *BuildConfig `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
	PrData       *PullRequest `protobuf:"bytes,2,opt,name=prData" json:"prData,omitempty"`
	VaultToken   string       `protobuf:"bytes,3,opt,name=vaultToken" json:"vaultToken,omitempty"`
	CheckoutHash string       `protobuf:"bytes,4,opt,name=checkoutHash" json:"checkoutHash,omitempty"`
}

func (m *PRBuildBundle) Reset()                    { *m = PRBuildBundle{} }
func (m *PRBuildBundle) String() string            { return proto.CompactTextString(m) }
func (*PRBuildBundle) ProtoMessage()               {}
func (*PRBuildBundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PRBuildBundle) GetConfig() *BuildConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *PRBuildBundle) GetPrData() *PullRequest {
	if m != nil {
		return m.PrData
	}
	return nil
}

func (m *PRBuildBundle) GetVaultToken() string {
	if m != nil {
		return m.VaultToken
	}
	return ""
}

func (m *PRBuildBundle) GetCheckoutHash() string {
	if m != nil {
		return m.CheckoutHash
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildConfig)(nil), "protos.BuildConfig")
	proto.RegisterType((*Stage)(nil), "protos.Stage")
	proto.RegisterType((*Result)(nil), "protos.Result")
	proto.RegisterType((*WerkerTask)(nil), "protos.WerkerTask")
	proto.RegisterType((*PushBuildBundle)(nil), "protos.PushBuildBundle")
	proto.RegisterType((*PRBuildBundle)(nil), "protos.PRBuildBundle")
	proto.RegisterEnum("protos.StageResultVal", StageResultVal_name, StageResultVal_value)
}

func init() { proto.RegisterFile("build.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xed, 0x8a, 0xd3, 0x40,
	0x14, 0x35, 0x4d, 0x9b, 0x6d, 0x6f, 0x6d, 0x2d, 0xa3, 0x2c, 0x63, 0x11, 0x29, 0x41, 0xa1, 0xb8,
	0xd2, 0xc5, 0xfa, 0x04, 0xbb, 0x7e, 0xa0, 0x20, 0x52, 0xa6, 0x45, 0x7f, 0x4f, 0xd3, 0x69, 0x13,
	0x32, 0xcd, 0xc4, 0x4c, 0xa6, 0xb2, 0xff, 0x7c, 0x21, 0x41, 0x7c, 0x27, 0xdf, 0x43, 0xe6, 0x66,
	0xd2, 0x0f, 0x45, 0x04, 0xf1, 0x57, 0xe7, 0x9c, 0x7b, 0xe6, 0xcc, 0xb9, 0xf7, 0x96, 0x40, 0x77,
	0x69, 0x12, 0xb9, 0x9a, 0xe4, 0x85, 0x2a, 0x15, 0x09, 0xf0, 0x47, 0x0f, 0x7b, 0x9f, 0xc5, 0x32,
	0x56, 0x2a, 0xad, 0xe8, 0xe1, 0xfd, 0x8d, 0x52, 0x1b, 0x29, 0x2e, 0x11, 0x2d, 0xcd, 0xfa, 0x92,
	0x67, 0x37, 0x55, 0x29, 0xfc, 0xee, 0x41, 0xf7, 0xda, 0x3a, 0xbc, 0x50, 0xd9, 0x3a, 0xd9, 0x90,
	0x7b, 0xd0, 0x4a, 0xb6, 0x7c, 0x23, 0xa8, 0x37, 0xf2, 0xc6, 0x1d, 0x56, 0x01, 0xf2, 0x00, 0x3a,
	0xf8, 0xcc, 0x42, 0x29, 0x49, 0x1b, 0x58, 0x39, 0x10, 0x64, 0x08, 0xed, 0x9c, 0x47, 0x29, 0xdf,
	0x08, 0x4d, 0xfd, 0x91, 0x3f, 0xee, 0xb0, 0x3d, 0xb6, 0xb5, 0x65, 0xc1, 0xb3, 0x28, 0x16, 0x9a,
	0x36, 0xab, 0x5a, 0x8d, 0xc9, 0x00, 0x7c, 0x91, 0xed, 0x68, 0x0b, 0x69, 0x7b, 0x24, 0x8f, 0x21,
	0xd0, 0x25, 0xfa, 0x9c, 0x8d, 0xfc, 0x71, 0x77, 0xda, 0xab, 0x52, 0xea, 0xc9, 0xdc, 0xb2, 0xcc,
	0x15, 0xc3, 0x57, 0xd0, 0x42, 0xa2, 0x76, 0xf0, 0x0e, 0x0e, 0xe7, 0x10, 0xe8, 0xa8, 0x48, 0xf2,
	0x92, 0x36, 0x90, 0x74, 0x88, 0x10, 0x68, 0x66, 0x7c, 0x2b, 0xa8, 0x8f, 0xe1, 0xf1, 0x1c, 0x7e,
	0xf1, 0x20, 0x60, 0x42, 0x1b, 0x59, 0xda, 0xb6, 0xd1, 0xbb, 0x6e, 0x1b, 0x01, 0x99, 0x60, 0x9c,
	0xd2, 0x68, 0xec, 0xb9, 0x3f, 0x3d, 0x3f, 0x8d, 0x83, 0x57, 0x3f, 0x70, 0xc9, 0x9c, 0xca, 0xba,
	0x88, 0xa2, 0x50, 0x85, 0x7b, 0xa5, 0x02, 0x76, 0x04, 0x5b, 0xa1, 0x35, 0xb6, 0xe5, 0x46, 0x50,
	0xe3, 0xf0, 0x87, 0x07, 0xf0, 0x51, 0x14, 0xa9, 0x28, 0x16, 0x5c, 0xa7, 0xe4, 0x21, 0xc0, 0x8e,
	0x1b, 0x59, 0x2e, 0x54, 0x2a, 0x32, 0x97, 0xe5, 0x88, 0x21, 0x21, 0xdc, 0x8e, 0x62, 0x11, 0xa5,
	0xca, 0x94, 0x6f, 0xb8, 0x8e, 0xdd, 0x2a, 0x4e, 0x38, 0xf2, 0xcc, 0xed, 0xca, 0x2e, 0x14, 0x83,
	0x74, 0xa7, 0x77, 0xeb, 0xdc, 0x47, 0x9b, 0x66, 0x07, 0x95, 0x4d, 0xb8, 0x8b, 0x74, 0xf5, 0x68,
	0x13, 0x2d, 0xf7, 0x98, 0x50, 0x38, 0xb3, 0xe7, 0x9b, 0x5c, 0xd0, 0x16, 0x96, 0x6a, 0x68, 0x6f,
	0xad, 0x8d, 0x94, 0xef, 0xed, 0x58, 0x83, 0xea, 0x56, 0x8d, 0x49, 0x1f, 0x1a, 0xc9, 0x8a, 0x9e,
	0x8d, 0xbc, 0xb1, 0xcf, 0x1a, 0xc9, 0x2a, 0xfc, 0xe6, 0xc1, 0x9d, 0x99, 0xd1, 0x31, 0x06, 0xb8,
	0x36, 0xd9, 0x4a, 0x0a, 0x72, 0x01, 0x41, 0x84, 0x51, 0xb0, 0xd1, 0x3f, 0xa4, 0x74, 0x12, 0xf2,
	0x14, 0xda, 0xb9, 0xd1, 0xf1, 0x4b, 0x5e, 0x72, 0xec, 0xba, 0x3b, 0x1d, 0xd4, 0x72, 0x26, 0x72,
	0x65, 0xbd, 0xd9, 0x5e, 0xf1, 0xcb, 0x1c, 0xfd, 0xbf, 0xce, 0xb1, 0xf9, 0xfb, 0x1c, 0xc3, 0xaf,
	0x1e, 0xf4, 0x66, 0xec, 0x9f, 0x03, 0x5f, 0x40, 0x90, 0x17, 0x47, 0x71, 0xf7, 0xe2, 0x99, 0x91,
	0x92, 0x89, 0x4f, 0x46, 0xe8, 0x92, 0x39, 0xc9, 0xff, 0xc8, 0xfb, 0xe4, 0x11, 0xf4, 0x4f, 0xff,
	0x96, 0xa4, 0x0d, 0xcd, 0xd9, 0xd5, 0x7c, 0x3e, 0xb8, 0x65, 0x4f, 0xaf, 0xaf, 0xde, 0xbe, 0x1b,
	0x78, 0xcb, 0xea, 0x0b, 0xf1, 0xfc, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xcd, 0x8a, 0xe5,
	0x37, 0x04, 0x00, 0x00,
}
