# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "..", "/home/vagrant/go/src/github.com/level11consulting/ocelot/", type: "rsync"

  config.vm.define "infra" do |infra|
    infra.vm.box = "ubuntu/bionic64"
    infra.vm.hostname = "infra"
    infra.vm.provider :virtualbox do |vb|
      vb.name = "infra"
      vb.memory = "2048"
  end

  # Use the vagrant provisioner to install Docker
  config.vm.provision "docker" do |d|
  end

  # Use ansible to provision host
  config.vm.provision "ansible" do |a|
    a.playbook = "infra-playbook.yml"
  end

  # Set static IP for this host  
  infra.vm.network "private_network", ip: "192.168.56.78"
  end

  config.vm.define "ocelot", primary: true do |ocelot|
    ocelot.vm.box = "ubuntu/bionic64"
    ocelot.vm.hostname = "ocelot"
    ocelot.vm.provider :virtualbox do |vb|
      vb.name = "ocelot"
      vb.memory = "2048"
  end

  # Use the vagrant provisioner to install Docker
  config.vm.provision "docker" do |d|
  end

  # Use ansible to provision host
  config.vm.provision "ansible" do |a|
    a.playbook = "ocelot-playbook.yml"
  end

  # Set static IP for this host  
  ocelot.vm.network "private_network", ip: "192.168.12.34"
  end

  # NOTE: This outer provision block runs FIRST before inner blocks of the VMs above
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt-get install -y ansible
  SHELL
end
