package buildcredsadd

import (
	"bitbucket.org/level11consulting/ocelot/admin/models"
	"bitbucket.org/level11consulting/ocelot/client/commandhelper"
	"bytes"
	"context"
	"flag"
	"github.com/golang/protobuf/ptypes/empty"
	"github.com/mitchellh/cli"
	"testing"
	"strings"
	"bitbucket.org/level11consulting/go-til/test"
)

// testNew will return the bare minimum. flags and fileloc of yaml will have to be set after instantiation
// or be generated by new functions
func testNew(inputReaderData []byte) *cmd {
	ui := cli.NewMockUi()
	if len(inputReaderData) >= 0 {
		ui.InputReader = bytes.NewReader(inputReaderData)
	}
	c := &cmd{
		UI: ui,
		config: commandhelper.NewTestClientConfig([]string{}),
	}
	c.flags = flag.NewFlagSet("", flag.ContinueOnError)
	c.flags.StringVar(&c.fileloc, "credfile-loc", "",
		"Location of yaml file containing creds to upload")
	return c
}

func Test_cmd_Run_Yaml(t *testing.T) {
	var input []byte
	ui := cli.NewMockUi()
	if len(input) >= 0 {
		ui.InputReader = bytes.NewReader(input)
	}
	c := &cmd{
		UI: ui,
		config: commandhelper.NewTestClientConfig([]string{}),
	}
	c.flags = flag.NewFlagSet("", flag.ContinueOnError)
	c.flags.StringVar(&c.fileloc, "credfile-loc", "",
		"Location of yaml file containing creds to upload")

	ctx := context.Background()
	c.fileloc = "./test-fixtures/newcreds.yml"
	expectedCreds := &models.CredWrapper{
		Vcs: []*models.VCSCreds{
			{
				ClientId:     "fancy-frickin-identification",
				ClientSecret: "SHH-BE-QUIET-ITS-A-SECRET",
				TokenURL:     "https://ocelot.perf/site/oauth2/access_token",
				AcctName:     "lamb-shank",
				Type:         "bitbucket",
				SshFileLoc:   "/home/mariannefeng/.ssh/id_rsa",
			},
		},
	}
	var args []string
	if exit := c.Run(args); exit != 1 {
		t.Fatal("should return exit 1 because SSH Key path doesn't exist")
	}
	uploadErrMsg := strings.TrimSpace(ui.ErrorWriter.String())
	expectedSSHErrMsg := `Could not read file at ./test-fixtures/newcreds.yml 
Error: open /home/mariannefeng/.ssh/id_rsa: no such file or directory`
	if uploadErrMsg != expectedSSHErrMsg {
		t.Error(test.StrFormatErrors("ssh key file error ouput", expectedSSHErrMsg, uploadErrMsg))
	}

	actualCreds, err := c.config.Client.GetVCSCreds(ctx, &empty.Empty{})
	if err != nil {
		t.Fatal("could not get actual creds from fake guide ocelot client")
	}
	if !models.CompareCredWrappers(expectedCreds, actualCreds) {
		t.Error("expected creds mismatch\n expected: ", expectedCreds, "\n actual: ", actualCreds)
	}


}

func Test_cmd_Run_noYaml(t *testing.T) {
	input := []byte(`fancy-frickin-identification
bitbucket
lamb-shank
https://ocelot.perf/site/oauth2/access_token
SHH-BE-QUIET-ITS-A-SECRET`)
	cmd := testNew(input)
	ctx := context.Background()
	expectedCreds := &models.CredWrapper{
		Vcs: []*models.VCSCreds{
			{
				ClientId:     "fancy-frickin-identification",
				ClientSecret: "SHH-BE-QUIET-ITS-A-SECRET",
				TokenURL:     "https://ocelot.perf/site/oauth2/access_token",
				AcctName:     "lamb-shank",
				Type:         "bitbucket",
			},
		},
	}

	var args []string
	exit := cmd.Run(args)
	if exit != 0 {
		t.Error("should return exit code 0, got ", exit)
	}
	sentCreds, err := cmd.config.Client.GetVCSCreds(ctx, &empty.Empty{})
	if err != nil {
		t.Fatal("could not get actual creds from fake guide ocelot client")
	}
	if !models.CompareCredWrappers(expectedCreds, sentCreds) {
		t.Error("expected creds mismatch\n expected: ", expectedCreds, "\n actual: ", sentCreds)
	}
}