// Code generated by protoc-gen-go. DO NOT EDIT.
// source: build.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StageResultVal int32

const (
	StageResultVal_PASS StageResultVal = 0
	StageResultVal_FAIL StageResultVal = 1
)

var StageResultVal_name = map[int32]string{
	0: "PASS",
	1: "FAIL",
}
var StageResultVal_value = map[string]int32{
	"PASS": 0,
	"FAIL": 1,
}

func (x StageResultVal) String() string {
	return proto.EnumName(StageResultVal_name, int32(x))
}
func (StageResultVal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{0}
}

// this is a direct translation of the ocelot.yaml file
type BuildConfig struct {
	// either image or machineTag is required
	// image is the docker image to run the build in
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// machineTag is the
	// @inject_tag: yaml:"machineTag"
	MachineTag string `protobuf:"bytes,9,opt,name=machineTag,proto3" json:"machineTag,omitempty" yaml:"machineTag"`
	// @inject_tag: yaml:"buildTool"
	BuildTool            string         `protobuf:"bytes,2,opt,name=buildTool,proto3" json:"buildTool,omitempty" yaml:"buildTool"`
	Packages             []string       `protobuf:"bytes,3,rep,name=packages,proto3" json:"packages,omitempty"`
	Branches             []string       `protobuf:"bytes,4,rep,name=branches,proto3" json:"branches,omitempty"`
	Env                  []string       `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	Stages               []*Stage       `protobuf:"bytes,7,rep,name=stages,proto3" json:"stages,omitempty"`
	Notify               *Notifications `protobuf:"bytes,8,opt,name=notify,proto3" json:"notify,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildConfig) Reset()         { *m = BuildConfig{} }
func (m *BuildConfig) String() string { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()    {}
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{0}
}
func (m *BuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfig.Unmarshal(m, b)
}
func (m *BuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfig.Marshal(b, m, deterministic)
}
func (dst *BuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfig.Merge(dst, src)
}
func (m *BuildConfig) XXX_Size() int {
	return xxx_messageInfo_BuildConfig.Size(m)
}
func (m *BuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfig proto.InternalMessageInfo

func (m *BuildConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *BuildConfig) GetMachineTag() string {
	if m != nil {
		return m.MachineTag
	}
	return ""
}

func (m *BuildConfig) GetBuildTool() string {
	if m != nil {
		return m.BuildTool
	}
	return ""
}

func (m *BuildConfig) GetPackages() []string {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *BuildConfig) GetBranches() []string {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *BuildConfig) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *BuildConfig) GetStages() []*Stage {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *BuildConfig) GetNotify() *Notifications {
	if m != nil {
		return m.Notify
	}
	return nil
}

type Stage struct {
	Env    []string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty"`
	Script []string `protobuf:"bytes,2,rep,name=script,proto3" json:"script,omitempty"`
	Name   string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: yaml:"trigger"
	Trigger              *Triggers `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty" yaml:"trigger"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Stage) Reset()         { *m = Stage{} }
func (m *Stage) String() string { return proto.CompactTextString(m) }
func (*Stage) ProtoMessage()    {}
func (*Stage) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{1}
}
func (m *Stage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stage.Unmarshal(m, b)
}
func (m *Stage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stage.Marshal(b, m, deterministic)
}
func (dst *Stage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stage.Merge(dst, src)
}
func (m *Stage) XXX_Size() int {
	return xxx_messageInfo_Stage.Size(m)
}
func (m *Stage) XXX_DiscardUnknown() {
	xxx_messageInfo_Stage.DiscardUnknown(m)
}

var xxx_messageInfo_Stage proto.InternalMessageInfo

func (m *Stage) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Stage) GetScript() []string {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *Stage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stage) GetTrigger() *Triggers {
	if m != nil {
		return m.Trigger
	}
	return nil
}

// todo: move to a new notifications.proto?
type Notifications struct {
	Slack                *Slack   `protobuf:"bytes,1,opt,name=slack,proto3" json:"slack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notifications) Reset()         { *m = Notifications{} }
func (m *Notifications) String() string { return proto.CompactTextString(m) }
func (*Notifications) ProtoMessage()    {}
func (*Notifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{2}
}
func (m *Notifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notifications.Unmarshal(m, b)
}
func (m *Notifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notifications.Marshal(b, m, deterministic)
}
func (dst *Notifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notifications.Merge(dst, src)
}
func (m *Notifications) XXX_Size() int {
	return xxx_messageInfo_Notifications.Size(m)
}
func (m *Notifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Notifications.DiscardUnknown(m)
}

var xxx_messageInfo_Notifications proto.InternalMessageInfo

func (m *Notifications) GetSlack() *Slack {
	if m != nil {
		return m.Slack
	}
	return nil
}

// todo: move to a new notifications.proto?
type Slack struct {
	// channel is which channel to post to. if empty, will be default channel set up by person who created url
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	//  identifier attached to url uploaded via `ocelot creds slack add`
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// on is what type of event to trigger a webhook on can be both PASS and FAIL
	On                   []StageResultVal `protobuf:"varint,3,rep,packed,name=on,proto3,enum=models.StageResultVal" json:"on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Slack) Reset()         { *m = Slack{} }
func (m *Slack) String() string { return proto.CompactTextString(m) }
func (*Slack) ProtoMessage()    {}
func (*Slack) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{3}
}
func (m *Slack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slack.Unmarshal(m, b)
}
func (m *Slack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slack.Marshal(b, m, deterministic)
}
func (dst *Slack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slack.Merge(dst, src)
}
func (m *Slack) XXX_Size() int {
	return xxx_messageInfo_Slack.Size(m)
}
func (m *Slack) XXX_DiscardUnknown() {
	xxx_messageInfo_Slack.DiscardUnknown(m)
}

var xxx_messageInfo_Slack proto.InternalMessageInfo

func (m *Slack) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Slack) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Slack) GetOn() []StageResultVal {
	if m != nil {
		return m.On
	}
	return nil
}

type Result struct {
	Stage                string         `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Status               StageResultVal `protobuf:"varint,2,opt,name=status,proto3,enum=models.StageResultVal" json:"status,omitempty"`
	Error                string         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Messages             []string       `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{4}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetStage() string {
	if m != nil {
		return m.Stage
	}
	return ""
}

func (m *Result) GetStatus() StageResultVal {
	if m != nil {
		return m.Status
	}
	return StageResultVal_PASS
}

func (m *Result) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Result) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Triggers struct {
	Branches             []string `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Triggers) Reset()         { *m = Triggers{} }
func (m *Triggers) String() string { return proto.CompactTextString(m) }
func (*Triggers) ProtoMessage()    {}
func (*Triggers) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{5}
}
func (m *Triggers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Triggers.Unmarshal(m, b)
}
func (m *Triggers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Triggers.Marshal(b, m, deterministic)
}
func (dst *Triggers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Triggers.Merge(dst, src)
}
func (m *Triggers) XXX_Size() int {
	return xxx_messageInfo_Triggers.Size(m)
}
func (m *Triggers) XXX_DiscardUnknown() {
	xxx_messageInfo_Triggers.DiscardUnknown(m)
}

var xxx_messageInfo_Triggers proto.InternalMessageInfo

func (m *Triggers) GetBranches() []string {
	if m != nil {
		return m.Branches
	}
	return nil
}

type WerkerTask struct {
	VaultToken           string       `protobuf:"bytes,1,opt,name=vaultToken,proto3" json:"vaultToken,omitempty"`
	CheckoutHash         string       `protobuf:"bytes,2,opt,name=checkoutHash,proto3" json:"checkoutHash,omitempty"`
	BuildConf            *BuildConfig `protobuf:"bytes,3,opt,name=buildConf,proto3" json:"buildConf,omitempty"`
	VcsToken             string       `protobuf:"bytes,4,opt,name=vcsToken,proto3" json:"vcsToken,omitempty"`
	VcsType              SubCredType  `protobuf:"varint,9,opt,name=vcsType,proto3,enum=models.SubCredType" json:"vcsType,omitempty"`
	FullName             string       `protobuf:"bytes,6,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Id                   int64        `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Branch               string       `protobuf:"bytes,8,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WerkerTask) Reset()         { *m = WerkerTask{} }
func (m *WerkerTask) String() string { return proto.CompactTextString(m) }
func (*WerkerTask) ProtoMessage()    {}
func (*WerkerTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_99c6a434dd33a48e, []int{6}
}
func (m *WerkerTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WerkerTask.Unmarshal(m, b)
}
func (m *WerkerTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WerkerTask.Marshal(b, m, deterministic)
}
func (dst *WerkerTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WerkerTask.Merge(dst, src)
}
func (m *WerkerTask) XXX_Size() int {
	return xxx_messageInfo_WerkerTask.Size(m)
}
func (m *WerkerTask) XXX_DiscardUnknown() {
	xxx_messageInfo_WerkerTask.DiscardUnknown(m)
}

var xxx_messageInfo_WerkerTask proto.InternalMessageInfo

func (m *WerkerTask) GetVaultToken() string {
	if m != nil {
		return m.VaultToken
	}
	return ""
}

func (m *WerkerTask) GetCheckoutHash() string {
	if m != nil {
		return m.CheckoutHash
	}
	return ""
}

func (m *WerkerTask) GetBuildConf() *BuildConfig {
	if m != nil {
		return m.BuildConf
	}
	return nil
}

func (m *WerkerTask) GetVcsToken() string {
	if m != nil {
		return m.VcsToken
	}
	return ""
}

func (m *WerkerTask) GetVcsType() SubCredType {
	if m != nil {
		return m.VcsType
	}
	return SubCredType_NIL_SCT
}

func (m *WerkerTask) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *WerkerTask) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WerkerTask) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildConfig)(nil), "models.BuildConfig")
	proto.RegisterType((*Stage)(nil), "models.Stage")
	proto.RegisterType((*Notifications)(nil), "models.Notifications")
	proto.RegisterType((*Slack)(nil), "models.Slack")
	proto.RegisterType((*Result)(nil), "models.Result")
	proto.RegisterType((*Triggers)(nil), "models.Triggers")
	proto.RegisterType((*WerkerTask)(nil), "models.WerkerTask")
	proto.RegisterEnum("models.StageResultVal", StageResultVal_name, StageResultVal_value)
}

func init() { proto.RegisterFile("build.proto", fileDescriptor_build_99c6a434dd33a48e) }

var fileDescriptor_build_99c6a434dd33a48e = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x61, 0x6b, 0xdb, 0x3c,
	0x10, 0x7e, 0xed, 0x24, 0x4e, 0x72, 0x7e, 0x1b, 0x82, 0xb6, 0x15, 0x51, 0xc6, 0x08, 0xde, 0x56,
	0x42, 0xa1, 0x81, 0x65, 0xfb, 0x03, 0x6d, 0x61, 0x6c, 0x30, 0xca, 0x70, 0xc2, 0x06, 0xfb, 0xa6,
	0xd8, 0xaa, 0x23, 0xec, 0x48, 0x99, 0x64, 0x07, 0xfa, 0x6d, 0xfb, 0x0b, 0xfb, 0xc5, 0x43, 0x67,
	0xa9, 0x89, 0x3f, 0xec, 0x9b, 0x9e, 0xe7, 0xce, 0x77, 0xba, 0x7b, 0x1e, 0x19, 0xe2, 0x4d, 0x23,
	0xaa, 0x7c, 0xb1, 0xd7, 0xaa, 0x56, 0x24, 0xda, 0xa9, 0x9c, 0x57, 0xe6, 0x22, 0xce, 0x34, 0xcf,
	0x4d, 0x4b, 0x26, 0xbf, 0x43, 0x88, 0x6f, 0x6d, 0xd2, 0x9d, 0x92, 0x0f, 0xa2, 0x20, 0xcf, 0x61,
	0x20, 0x76, 0xac, 0xe0, 0x34, 0x98, 0x05, 0xf3, 0x71, 0xda, 0x02, 0xf2, 0x0a, 0x60, 0xc7, 0xb2,
	0xad, 0x90, 0x7c, 0xcd, 0x0a, 0x3a, 0xc6, 0xd0, 0x09, 0x43, 0x5e, 0xc2, 0x18, 0x3b, 0xad, 0x95,
	0xaa, 0x68, 0x88, 0xe1, 0x23, 0x41, 0x2e, 0x60, 0xb4, 0x67, 0x59, 0xc9, 0x0a, 0x6e, 0x68, 0x6f,
	0xd6, 0x9b, 0x8f, 0xd3, 0x27, 0x6c, 0x63, 0x1b, 0xcd, 0x64, 0xb6, 0xe5, 0x86, 0xf6, 0xdb, 0x98,
	0xc7, 0x64, 0x0a, 0x3d, 0x2e, 0x0f, 0x74, 0x80, 0xb4, 0x3d, 0x92, 0xb7, 0x10, 0x99, 0x1a, 0xeb,
	0x0c, 0x67, 0xbd, 0x79, 0xbc, 0x3c, 0x5b, 0xb4, 0x33, 0x2d, 0x56, 0x96, 0x4d, 0x5d, 0x90, 0x5c,
	0x43, 0x24, 0x55, 0x2d, 0x1e, 0x1e, 0xe9, 0x68, 0x16, 0xcc, 0xe3, 0xe5, 0x0b, 0x9f, 0x76, 0x6f,
	0x59, 0x91, 0xb1, 0x5a, 0x28, 0x69, 0x52, 0x97, 0x94, 0xfc, 0x84, 0x01, 0x7e, 0xef, 0x1b, 0x06,
	0xc7, 0x86, 0xe7, 0x10, 0x99, 0x4c, 0x8b, 0x7d, 0x4d, 0x43, 0x24, 0x1d, 0x22, 0x04, 0xfa, 0x92,
	0xed, 0x38, 0xed, 0xe1, 0xac, 0x78, 0x26, 0x57, 0x30, 0xac, 0xb5, 0x28, 0x0a, 0xae, 0x69, 0x1f,
	0xdb, 0x4e, 0x7d, 0xdb, 0x75, 0x4b, 0x9b, 0xd4, 0x27, 0x24, 0x1f, 0xe0, 0xac, 0x73, 0x17, 0xf2,
	0x1a, 0x06, 0xa6, 0x62, 0x59, 0x89, 0x7b, 0x3f, 0x1d, 0xcc, 0x92, 0x69, 0x1b, 0x4b, 0x04, 0x0c,
	0x10, 0x13, 0x0a, 0xc3, 0x6c, 0xcb, 0xa4, 0xe4, 0x95, 0xd3, 0xc9, 0x43, 0xab, 0x94, 0xc8, 0xb9,
	0xb4, 0xa5, 0xb9, 0x76, 0x52, 0x9c, 0x30, 0xe4, 0x12, 0x42, 0x25, 0x51, 0x85, 0xc9, 0xf2, 0xbc,
	0xbb, 0x3d, 0x6e, 0x9a, 0xaa, 0xfe, 0xc6, 0xaa, 0x34, 0x54, 0x32, 0xf9, 0x15, 0x40, 0xd4, 0x32,
	0xd6, 0x12, 0xb8, 0x57, 0x6f, 0x09, 0x04, 0x64, 0x81, 0x52, 0xd4, 0x8d, 0xc1, 0x26, 0xff, 0x2e,
	0xe6, 0xb2, 0x6c, 0x15, 0xae, 0xb5, 0xd2, 0x6e, 0x65, 0x2d, 0xb0, 0xf2, 0xef, 0xb8, 0x31, 0x28,
	0xa9, 0x93, 0xdf, 0xe3, 0xe4, 0x12, 0x46, 0x7e, 0x71, 0x1d, 0x9b, 0x04, 0x5d, 0x9b, 0x24, 0x7f,
	0x42, 0x80, 0xef, 0x5c, 0x97, 0x5c, 0xaf, 0x99, 0x29, 0xed, 0x06, 0x0e, 0xac, 0xa9, 0xea, 0xb5,
	0x2a, 0xb9, 0x74, 0x77, 0x3e, 0x61, 0x48, 0x02, 0xff, 0x67, 0x5b, 0x9e, 0x95, 0xaa, 0xa9, 0x3f,
	0x31, 0xb3, 0x75, 0x3b, 0xea, 0x70, 0xe4, 0x9d, 0xf3, 0xb3, 0x7d, 0x14, 0x78, 0xe1, 0x78, 0xf9,
	0xcc, 0xcf, 0x77, 0xf2, 0x5a, 0xd2, 0x63, 0x96, 0xbd, 0xe1, 0x21, 0x33, 0x6d, 0xd3, 0x3e, 0x96,
	0x7c, 0xc2, 0xe4, 0x1a, 0x86, 0xf6, 0xfc, 0xb8, 0xe7, 0xf8, 0x76, 0x26, 0xc7, 0x62, 0xab, 0x66,
	0x73, 0xa7, 0x79, 0x6e, 0x43, 0xa9, 0xcf, 0xb1, 0xa5, 0x1e, 0x9a, 0xaa, 0xba, 0xb7, 0x06, 0x8b,
	0xda, 0x52, 0x1e, 0x93, 0x09, 0x84, 0x22, 0xa7, 0xc3, 0x59, 0x30, 0xef, 0xa5, 0xa1, 0xc8, 0xad,
	0x41, 0xdb, 0x45, 0xa0, 0xd5, 0xc7, 0xa9, 0x43, 0x57, 0x6f, 0x60, 0xd2, 0x15, 0x82, 0x8c, 0xa0,
	0xff, 0xf5, 0x66, 0xb5, 0x9a, 0xfe, 0x67, 0x4f, 0x1f, 0x6f, 0x3e, 0x7f, 0x99, 0x06, 0xb7, 0xfd,
	0x1f, 0xe1, 0x7e, 0xb3, 0x89, 0xf0, 0x57, 0xf0, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70,
	0x59, 0xe3, 0x02, 0x2e, 0x04, 0x00, 0x00,
}
