// Code generated by protoc-gen-go. DO NOT EDIT.
// source: guideocelot.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CredType int32

const (
	CredType_NIL_CT CredType = 0
	CredType_VCS    CredType = 1
	CredType_REPO   CredType = 2
	CredType_K8S    CredType = 3
	CredType_SSH    CredType = 5
)

var CredType_name = map[int32]string{
	0: "NIL_CT",
	1: "VCS",
	2: "REPO",
	3: "K8S",
	5: "SSH",
}
var CredType_value = map[string]int32{
	"NIL_CT": 0,
	"VCS":    1,
	"REPO":   2,
	"K8S":    3,
	"SSH":    5,
}

func (x CredType) String() string {
	return proto.EnumName(CredType_name, int32(x))
}
func (CredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type SubCredType int32

const (
	SubCredType_NIL_SCT SubCredType = 0
	// BITBUCKET is a child of VCS
	SubCredType_BITBUCKET SubCredType = 1
	// GITHUB is a child of VCS
	SubCredType_GITHUB SubCredType = 2
	// NEXUS is a child of REPO
	SubCredType_NEXUS SubCredType = 3
	// MAVEN is a child of REPO
	SubCredType_MAVEN SubCredType = 4
	// DOCKER is a child of REPO
	SubCredType_DOCKER SubCredType = 5
	// KUBECONF is a child of K8S
	SubCredType_KUBECONF SubCredType = 6
	// SSHKEY is a child of SSH
	SubCredType_SSHKEY SubCredType = 8
)

var SubCredType_name = map[int32]string{
	0: "NIL_SCT",
	1: "BITBUCKET",
	2: "GITHUB",
	3: "NEXUS",
	4: "MAVEN",
	5: "DOCKER",
	6: "KUBECONF",
	8: "SSHKEY",
}
var SubCredType_value = map[string]int32{
	"NIL_SCT":   0,
	"BITBUCKET": 1,
	"GITHUB":    2,
	"NEXUS":     3,
	"MAVEN":     4,
	"DOCKER":    5,
	"KUBECONF":  6,
	"SSHKEY":    8,
}

func (x SubCredType) String() string {
	return proto.EnumName(SubCredType_name, int32(x))
}
func (SubCredType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type BuildReq struct {
	// acctRepo is the ocelot account to which the creds are uploaded and the repository you wish to operate on, in the form account/repo
	AcctRepo string `protobuf:"bytes,1,opt,name=acctRepo" json:"acctRepo,omitempty"`
	// hash is the git hash to trigger.
	Hash string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	// branch is the branch that corresponds to the git hash. if the git hash has never been built by ocelot, this field is required.
	Branch string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
}

func (m *BuildReq) Reset()                    { *m = BuildReq{} }
func (m *BuildReq) String() string            { return proto.CompactTextString(m) }
func (*BuildReq) ProtoMessage()               {}
func (*BuildReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *BuildReq) GetAcctRepo() string {
	if m != nil {
		return m.AcctRepo
	}
	return ""
}

func (m *BuildReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildReq) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

type AllCredsWrapper struct {
	// All repository credentials for integrations
	// @inject_tag: yaml:"repoCreds"
	RepoCreds *RepoCredWrapper `protobuf:"bytes,1,opt,name=repoCreds" json:"repoCreds,omitempty" yaml:"repoCreds"`
	// All VCS credentials for building
	// @inject_tag: yaml:"vcsCreds"
	VcsCreds *CredWrapper `protobuf:"bytes,3,opt,name=vcsCreds" json:"vcsCreds,omitempty" yaml:"vcsCreds"`
}

func (m *AllCredsWrapper) Reset()                    { *m = AllCredsWrapper{} }
func (m *AllCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*AllCredsWrapper) ProtoMessage()               {}
func (*AllCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AllCredsWrapper) GetRepoCreds() *RepoCredWrapper {
	if m != nil {
		return m.RepoCreds
	}
	return nil
}

func (m *AllCredsWrapper) GetVcsCreds() *CredWrapper {
	if m != nil {
		return m.VcsCreds
	}
	return nil
}

// just a container for a list of VCSCreds
type CredWrapper struct {
	Vcs []*VCSCreds `protobuf:"bytes,2,rep,name=vcs" json:"vcs,omitempty"`
}

func (m *CredWrapper) Reset()                    { *m = CredWrapper{} }
func (m *CredWrapper) String() string            { return proto.CompactTextString(m) }
func (*CredWrapper) ProtoMessage()               {}
func (*CredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CredWrapper) GetVcs() []*VCSCreds {
	if m != nil {
		return m.Vcs
	}
	return nil
}

type SSHKeyWrapper struct {
	// account name to associate ssh key with
	AcctName string `protobuf:"bytes,1,opt,name=acctName" json:"acctName,omitempty"`
	// the contents of the private key
	PrivateKey []byte      `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	SubType    SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty"`
	// identifier is the unique identifier for when an ssh key is not associated with a VCS account.
	Identifier string `protobuf:"bytes,11,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *SSHKeyWrapper) Reset()                    { *m = SSHKeyWrapper{} }
func (m *SSHKeyWrapper) String() string            { return proto.CompactTextString(m) }
func (*SSHKeyWrapper) ProtoMessage()               {}
func (*SSHKeyWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SSHKeyWrapper) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *SSHKeyWrapper) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *SSHKeyWrapper) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

func (m *SSHKeyWrapper) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type SSHWrap struct {
	Keys []*SSHKeyWrapper `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
}

func (m *SSHWrap) Reset()                    { *m = SSHWrap{} }
func (m *SSHWrap) String() string            { return proto.CompactTextString(m) }
func (*SSHWrap) ProtoMessage()               {}
func (*SSHWrap) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *SSHWrap) GetKeys() []*SSHKeyWrapper {
	if m != nil {
		return m.Keys
	}
	return nil
}

type VCSCreds struct {
	// clientId is generated by creating an oAuth consumer in bitbucket. it is required to generate tokens.
	// @inject_tag: yaml:"clientId"
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty" yaml:"clientId"`
	// clientSecret is generated by creating an oAuth consumer in bitbucket. it is required to generate tokens.
	// @inject_tag: yaml:"clientSecret"
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret" json:"clientSecret,omitempty" yaml:"clientSecret"`
	// identifier is the name the user calls teh credential set
	Identifier string `protobuf:"bytes,8,opt,name=identifier" json:"identifier,omitempty"`
	// tokenUrl is the url at which to retrieve the token
	// @inject_tag: yaml:"tokenURL"
	TokenURL string `protobuf:"bytes,3,opt,name=tokenURL" json:"tokenURL,omitempty" yaml:"tokenURL"`
	// @inject_tag: yaml:"acctName"
	// acctName is the account to associate the VCSCred with. Must be the account name of the owner of the repository they wish to track (ie level11consulting)
	AcctName string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty" yaml:"acctName"`
	// just a string that says whether or not there is an ssh key on file
	// @inject_tag: yaml:"sshFileLoc"
	SshFileLoc string `protobuf:"bytes,6,opt,name=sshFileLoc" json:"sshFileLoc,omitempty" yaml:"sshFileLoc"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *VCSCreds) Reset()                    { *m = VCSCreds{} }
func (m *VCSCreds) String() string            { return proto.CompactTextString(m) }
func (*VCSCreds) ProtoMessage()               {}
func (*VCSCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *VCSCreds) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VCSCreds) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *VCSCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *VCSCreds) GetTokenURL() string {
	if m != nil {
		return m.TokenURL
	}
	return ""
}

func (m *VCSCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *VCSCreds) GetSshFileLoc() string {
	if m != nil {
		return m.SshFileLoc
	}
	return ""
}

func (m *VCSCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

// container for list of repo creds
type RepoCredWrapper struct {
	Repo []*RepoCreds `protobuf:"bytes,3,rep,name=repo" json:"repo,omitempty"`
}

func (m *RepoCredWrapper) Reset()                    { *m = RepoCredWrapper{} }
func (m *RepoCredWrapper) String() string            { return proto.CompactTextString(m) }
func (*RepoCredWrapper) ProtoMessage()               {}
func (*RepoCredWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *RepoCredWrapper) GetRepo() []*RepoCreds {
	if m != nil {
		return m.Repo
	}
	return nil
}

type RepoCreds struct {
	// username of repository
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	// password of repository
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	// @inject_tag: yaml:"repoUrl"
	RepoUrl    string `protobuf:"bytes,6,opt,name=repoUrl" json:"repoUrl,omitempty" yaml:"repoUrl"`
	Identifier string `protobuf:"bytes,8,opt,name=identifier" json:"identifier,omitempty"`
	// @inject_tag: yaml:"acctName"
	// account name (same as from vcs)
	AcctName string `protobuf:"bytes,4,opt,name=acctName" json:"acctName,omitempty" yaml:"acctName"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,10,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *RepoCreds) Reset()                    { *m = RepoCreds{} }
func (m *RepoCreds) String() string            { return proto.CompactTextString(m) }
func (*RepoCreds) ProtoMessage()               {}
func (*RepoCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *RepoCreds) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RepoCreds) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RepoCreds) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

func (m *RepoCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *RepoCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *RepoCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

type K8SCreds struct {
	// account name to associate this credential with
	AcctName string `protobuf:"bytes,1,opt,name=acctName" json:"acctName,omitempty"`
	// k8scontents is the contents of the kubeconfig file
	K8SContents string `protobuf:"bytes,2,opt,name=k8sContents" json:"k8sContents,omitempty"`
	// identifier in K8s creds is currently irrelevant, as there can only be one per account
	Identifier string `protobuf:"bytes,3,opt,name=identifier" json:"identifier,omitempty"`
	// @inject_tag: yaml:"subType"
	SubType SubCredType `protobuf:"varint,5,opt,name=subType,enum=models.SubCredType" json:"subType,omitempty" yaml:"subType"`
}

func (m *K8SCreds) Reset()                    { *m = K8SCreds{} }
func (m *K8SCreds) String() string            { return proto.CompactTextString(m) }
func (*K8SCreds) ProtoMessage()               {}
func (*K8SCreds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *K8SCreds) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *K8SCreds) GetK8SContents() string {
	if m != nil {
		return m.K8SContents
	}
	return ""
}

func (m *K8SCreds) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *K8SCreds) GetSubType() SubCredType {
	if m != nil {
		return m.SubType
	}
	return SubCredType_NIL_SCT
}

type K8SCredsWrapper struct {
	K8SCreds []*K8SCreds `protobuf:"bytes,2,rep,name=K8SCreds" json:"K8SCreds,omitempty"`
}

func (m *K8SCredsWrapper) Reset()                    { *m = K8SCredsWrapper{} }
func (m *K8SCredsWrapper) String() string            { return proto.CompactTextString(m) }
func (*K8SCredsWrapper) ProtoMessage()               {}
func (*K8SCredsWrapper) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *K8SCredsWrapper) GetK8SCreds() []*K8SCreds {
	if m != nil {
		return m.K8SCreds
	}
	return nil
}

type StatusQuery struct {
	// hash is the git hash to get status of
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	// acctName is the corresponding account that the hash is attached to
	AcctName string `protobuf:"bytes,2,opt,name=acctName" json:"acctName,omitempty"`
	// repoName is the corresponding repo name that the hash is attached to
	RepoName string `protobuf:"bytes,3,opt,name=repoName" json:"repoName,omitempty"`
	// partialRepo is just the first n letters of repo
	PartialRepo string `protobuf:"bytes,4,opt,name=partialRepo" json:"partialRepo,omitempty"`
}

func (m *StatusQuery) Reset()                    { *m = StatusQuery{} }
func (m *StatusQuery) String() string            { return proto.CompactTextString(m) }
func (*StatusQuery) ProtoMessage()               {}
func (*StatusQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *StatusQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *StatusQuery) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *StatusQuery) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *StatusQuery) GetPartialRepo() string {
	if m != nil {
		return m.PartialRepo
	}
	return ""
}

type BuildQuery struct {
	Hash    string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	BuildId int64  `protobuf:"varint,2,opt,name=buildId" json:"buildId,omitempty"`
}

func (m *BuildQuery) Reset()                    { *m = BuildQuery{} }
func (m *BuildQuery) String() string            { return proto.CompactTextString(m) }
func (*BuildQuery) ProtoMessage()               {}
func (*BuildQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *BuildQuery) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildQuery) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

type Builds struct {
	Builds map[string]*BuildRuntimeInfo `protobuf:"bytes,1,rep,name=builds" json:"builds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Builds) Reset()                    { *m = Builds{} }
func (m *Builds) String() string            { return proto.CompactTextString(m) }
func (*Builds) ProtoMessage()               {}
func (*Builds) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *Builds) GetBuilds() map[string]*BuildRuntimeInfo {
	if m != nil {
		return m.Builds
	}
	return nil
}

type BuildRuntimeInfo struct {
	// done says whether or not the build has completed
	Done bool `protobuf:"varint,1,opt,name=done" json:"done,omitempty"`
	// ip is the ip of the werker node that is running the build
	Ip string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	// grpcPort is the grpc port of the werker running the build
	GrpcPort string `protobuf:"bytes,3,opt,name=grpcPort" json:"grpcPort,omitempty"`
	// hash is the hash
	Hash     string `protobuf:"bytes,4,opt,name=hash" json:"hash,omitempty"`
	AcctName string `protobuf:"bytes,5,opt,name=acctName" json:"acctName,omitempty"`
	RepoName string `protobuf:"bytes,6,opt,name=repoName" json:"repoName,omitempty"`
	WsPort   string `protobuf:"bytes,7,opt,name=wsPort" json:"wsPort,omitempty"`
}

func (m *BuildRuntimeInfo) Reset()                    { *m = BuildRuntimeInfo{} }
func (m *BuildRuntimeInfo) String() string            { return proto.CompactTextString(m) }
func (*BuildRuntimeInfo) ProtoMessage()               {}
func (*BuildRuntimeInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *BuildRuntimeInfo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *BuildRuntimeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BuildRuntimeInfo) GetGrpcPort() string {
	if m != nil {
		return m.GrpcPort
	}
	return ""
}

func (m *BuildRuntimeInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildRuntimeInfo) GetAcctName() string {
	if m != nil {
		return m.AcctName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *BuildRuntimeInfo) GetWsPort() string {
	if m != nil {
		return m.WsPort
	}
	return ""
}

type LineResponse struct {
	OutputLine string `protobuf:"bytes,1,opt,name=outputLine" json:"outputLine,omitempty"`
}

func (m *LineResponse) Reset()                    { *m = LineResponse{} }
func (m *LineResponse) String() string            { return proto.CompactTextString(m) }
func (*LineResponse) ProtoMessage()               {}
func (*LineResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *LineResponse) GetOutputLine() string {
	if m != nil {
		return m.OutputLine
	}
	return ""
}

type RepoAccount struct {
	Repo    string `protobuf:"bytes,1,opt,name=repo" json:"repo,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Limit   int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *RepoAccount) Reset()                    { *m = RepoAccount{} }
func (m *RepoAccount) String() string            { return proto.CompactTextString(m) }
func (*RepoAccount) ProtoMessage()               {}
func (*RepoAccount) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *RepoAccount) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *RepoAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RepoAccount) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Status struct {
	BuildSum   *BuildSummary  `protobuf:"bytes,1,opt,name=buildSum" json:"buildSum,omitempty"`
	Stages     []*StageStatus `protobuf:"bytes,2,rep,name=stages" json:"stages,omitempty"`
	IsInConsul bool           `protobuf:"varint,3,opt,name=isInConsul" json:"isInConsul,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *Status) GetBuildSum() *BuildSummary {
	if m != nil {
		return m.BuildSum
	}
	return nil
}

func (m *Status) GetStages() []*StageStatus {
	if m != nil {
		return m.Stages
	}
	return nil
}

func (m *Status) GetIsInConsul() bool {
	if m != nil {
		return m.IsInConsul
	}
	return false
}

type StageStatus struct {
	StageStatus   string                      `protobuf:"bytes,1,opt,name=StageStatus" json:"StageStatus,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Status        int32                       `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Messages      []string                    `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	StartTime     *google_protobuf2.Timestamp `protobuf:"bytes,5,opt,name=startTime" json:"startTime,omitempty"`
	StageDuration float64                     `protobuf:"fixed64,6,opt,name=stageDuration" json:"stageDuration,omitempty"`
}

func (m *StageStatus) Reset()                    { *m = StageStatus{} }
func (m *StageStatus) String() string            { return proto.CompactTextString(m) }
func (*StageStatus) ProtoMessage()               {}
func (*StageStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *StageStatus) GetStageStatus() string {
	if m != nil {
		return m.StageStatus
	}
	return ""
}

func (m *StageStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StageStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StageStatus) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *StageStatus) GetStartTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *StageStatus) GetStageDuration() float64 {
	if m != nil {
		return m.StageDuration
	}
	return 0
}

type BuildSummary struct {
	Hash          string                      `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Failed        bool                        `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	BuildTime     *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=buildTime" json:"buildTime,omitempty"`
	Account       string                      `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	BuildDuration float64                     `protobuf:"fixed64,5,opt,name=buildDuration" json:"buildDuration,omitempty"`
	Repo          string                      `protobuf:"bytes,6,opt,name=repo" json:"repo,omitempty"`
	Branch        string                      `protobuf:"bytes,7,opt,name=branch" json:"branch,omitempty"`
	BuildId       int64                       `protobuf:"varint,8,opt,name=buildId" json:"buildId,omitempty"`
	QueueTime     *google_protobuf2.Timestamp `protobuf:"bytes,9,opt,name=queueTime" json:"queueTime,omitempty"`
}

func (m *BuildSummary) Reset()                    { *m = BuildSummary{} }
func (m *BuildSummary) String() string            { return proto.CompactTextString(m) }
func (*BuildSummary) ProtoMessage()               {}
func (*BuildSummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *BuildSummary) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BuildSummary) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *BuildSummary) GetBuildTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.BuildTime
	}
	return nil
}

func (m *BuildSummary) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *BuildSummary) GetBuildDuration() float64 {
	if m != nil {
		return m.BuildDuration
	}
	return 0
}

func (m *BuildSummary) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *BuildSummary) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuildSummary) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *BuildSummary) GetQueueTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.QueueTime
	}
	return nil
}

type Summaries struct {
	Sums []*BuildSummary `protobuf:"bytes,1,rep,name=sums" json:"sums,omitempty"`
}

func (m *Summaries) Reset()                    { *m = Summaries{} }
func (m *Summaries) String() string            { return proto.CompactTextString(m) }
func (*Summaries) ProtoMessage()               {}
func (*Summaries) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *Summaries) GetSums() []*BuildSummary {
	if m != nil {
		return m.Sums
	}
	return nil
}

type PollRequest struct {
	Account      string                      `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Repo         string                      `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
	Cron         string                      `protobuf:"bytes,4,opt,name=cron" json:"cron,omitempty"`
	Branches     string                      `protobuf:"bytes,5,opt,name=branches" json:"branches,omitempty"`
	LastCronTime *google_protobuf2.Timestamp `protobuf:"bytes,6,opt,name=lastCronTime" json:"lastCronTime,omitempty"`
	LastHashes   map[string]string           `protobuf:"bytes,7,rep,name=lastHashes" json:"lastHashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PollRequest) Reset()                    { *m = PollRequest{} }
func (m *PollRequest) String() string            { return proto.CompactTextString(m) }
func (*PollRequest) ProtoMessage()               {}
func (*PollRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *PollRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PollRequest) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *PollRequest) GetCron() string {
	if m != nil {
		return m.Cron
	}
	return ""
}

func (m *PollRequest) GetBranches() string {
	if m != nil {
		return m.Branches
	}
	return ""
}

func (m *PollRequest) GetLastCronTime() *google_protobuf2.Timestamp {
	if m != nil {
		return m.LastCronTime
	}
	return nil
}

func (m *PollRequest) GetLastHashes() map[string]string {
	if m != nil {
		return m.LastHashes
	}
	return nil
}

type Polls struct {
	Polls []*PollRequest `protobuf:"bytes,1,rep,name=polls" json:"polls,omitempty"`
}

func (m *Polls) Reset()                    { *m = Polls{} }
func (m *Polls) String() string            { return proto.CompactTextString(m) }
func (*Polls) ProtoMessage()               {}
func (*Polls) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *Polls) GetPolls() []*PollRequest {
	if m != nil {
		return m.Polls
	}
	return nil
}

type Exists struct {
	Exists bool `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
}

func (m *Exists) Reset()                    { *m = Exists{} }
func (m *Exists) String() string            { return proto.CompactTextString(m) }
func (*Exists) ProtoMessage()               {}
func (*Exists) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *Exists) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*BuildReq)(nil), "models.BuildReq")
	proto.RegisterType((*AllCredsWrapper)(nil), "models.AllCredsWrapper")
	proto.RegisterType((*CredWrapper)(nil), "models.CredWrapper")
	proto.RegisterType((*SSHKeyWrapper)(nil), "models.SSHKeyWrapper")
	proto.RegisterType((*SSHWrap)(nil), "models.SSHWrap")
	proto.RegisterType((*VCSCreds)(nil), "models.VCSCreds")
	proto.RegisterType((*RepoCredWrapper)(nil), "models.RepoCredWrapper")
	proto.RegisterType((*RepoCreds)(nil), "models.RepoCreds")
	proto.RegisterType((*K8SCreds)(nil), "models.K8SCreds")
	proto.RegisterType((*K8SCredsWrapper)(nil), "models.K8SCredsWrapper")
	proto.RegisterType((*StatusQuery)(nil), "models.StatusQuery")
	proto.RegisterType((*BuildQuery)(nil), "models.BuildQuery")
	proto.RegisterType((*Builds)(nil), "models.Builds")
	proto.RegisterType((*BuildRuntimeInfo)(nil), "models.BuildRuntimeInfo")
	proto.RegisterType((*LineResponse)(nil), "models.LineResponse")
	proto.RegisterType((*RepoAccount)(nil), "models.RepoAccount")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*StageStatus)(nil), "models.StageStatus")
	proto.RegisterType((*BuildSummary)(nil), "models.BuildSummary")
	proto.RegisterType((*Summaries)(nil), "models.Summaries")
	proto.RegisterType((*PollRequest)(nil), "models.PollRequest")
	proto.RegisterType((*Polls)(nil), "models.Polls")
	proto.RegisterType((*Exists)(nil), "models.Exists")
	proto.RegisterEnum("models.CredType", CredType_name, CredType_value)
	proto.RegisterEnum("models.SubCredType", SubCredType_name, SubCredType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GuideOcelot service

type GuideOcelotClient interface {
	GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error)
	SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	UpdateVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	VCSCredExists(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*Exists, error)
	CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	UpdateRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	RepoCredExists(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*Exists, error)
	UpdateK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	K8SCredExists(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*Exists, error)
	UpdateSSHCreds(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SSHCredExists(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*Exists, error)
	SetSSHCreds(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetSSHCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SSHWrap, error)
	GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error)
	SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	SetK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetK8SCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*K8SCredsWrapper, error)
	GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error)
	BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error)
	Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error)
	LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error)
	GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error)
	WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error)
	PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	DeletePollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	ListPolledRepos(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Polls, error)
	FindWerker(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRuntimeInfo, error)
}

type guideOcelotClient struct {
	cc *grpc.ClientConn
}

func NewGuideOcelotClient(cc *grpc.ClientConn) GuideOcelotClient {
	return &guideOcelotClient{cc}
}

func (c *guideOcelotClient) GetVCSCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CredWrapper, error) {
	out := new(CredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateVCSCreds(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateVCSCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) VCSCredExists(ctx context.Context, in *VCSCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/VCSCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) CheckConn(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/CheckConn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetVCSPrivateKey(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetVCSPrivateKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) RepoCredExists(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/RepoCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) K8SCredExists(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/K8SCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) UpdateSSHCreds(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/UpdateSSHCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SSHCredExists(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*Exists, error) {
	out := new(Exists)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SSHCredExists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetSSHCreds(ctx context.Context, in *SSHKeyWrapper, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetSSHCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetSSHCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*SSHWrap, error) {
	out := new(SSHWrap)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetSSHCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetRepoCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*RepoCredWrapper, error) {
	out := new(RepoCredWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetRepoCreds(ctx context.Context, in *RepoCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetRepoCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) SetK8SCreds(ctx context.Context, in *K8SCreds, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/SetK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetK8SCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*K8SCredsWrapper, error) {
	out := new(K8SCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetK8SCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetAllCreds(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*AllCredsWrapper, error) {
	out := new(AllCredsWrapper)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetAllCreds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRuntime(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (*Builds, error) {
	out := new(Builds)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/BuildRuntime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) Logs(ctx context.Context, in *BuildQuery, opts ...grpc.CallOption) (GuideOcelot_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[0], c.cc, "/models.GuideOcelot/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_LogsClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotLogsClient struct {
	grpc.ClientStream
}

func (x *guideOcelotLogsClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) LastFewSummaries(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*Summaries, error) {
	out := new(Summaries)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/LastFewSummaries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) GetStatus(ctx context.Context, in *StatusQuery, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) WatchRepo(ctx context.Context, in *RepoAccount, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/WatchRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) BuildRepoAndHash(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (GuideOcelot_BuildRepoAndHashClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GuideOcelot_serviceDesc.Streams[1], c.cc, "/models.GuideOcelot/BuildRepoAndHash", opts...)
	if err != nil {
		return nil, err
	}
	x := &guideOcelotBuildRepoAndHashClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuideOcelot_BuildRepoAndHashClient interface {
	Recv() (*LineResponse, error)
	grpc.ClientStream
}

type guideOcelotBuildRepoAndHashClient struct {
	grpc.ClientStream
}

func (x *guideOcelotBuildRepoAndHashClient) Recv() (*LineResponse, error) {
	m := new(LineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guideOcelotClient) PollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/PollRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) DeletePollRepo(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/DeletePollRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) ListPolledRepos(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Polls, error) {
	out := new(Polls)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/ListPolledRepos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideOcelotClient) FindWerker(ctx context.Context, in *BuildReq, opts ...grpc.CallOption) (*BuildRuntimeInfo, error) {
	out := new(BuildRuntimeInfo)
	err := grpc.Invoke(ctx, "/models.GuideOcelot/FindWerker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GuideOcelot service

type GuideOcelotServer interface {
	GetVCSCreds(context.Context, *google_protobuf.Empty) (*CredWrapper, error)
	SetVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	UpdateVCSCreds(context.Context, *VCSCreds) (*google_protobuf.Empty, error)
	VCSCredExists(context.Context, *VCSCreds) (*Exists, error)
	CheckConn(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
	SetVCSPrivateKey(context.Context, *SSHKeyWrapper) (*google_protobuf.Empty, error)
	UpdateRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	RepoCredExists(context.Context, *RepoCreds) (*Exists, error)
	UpdateK8SCreds(context.Context, *K8SCreds) (*google_protobuf.Empty, error)
	K8SCredExists(context.Context, *K8SCreds) (*Exists, error)
	UpdateSSHCreds(context.Context, *SSHKeyWrapper) (*google_protobuf.Empty, error)
	SSHCredExists(context.Context, *SSHKeyWrapper) (*Exists, error)
	SetSSHCreds(context.Context, *SSHKeyWrapper) (*google_protobuf.Empty, error)
	GetSSHCreds(context.Context, *google_protobuf.Empty) (*SSHWrap, error)
	GetRepoCreds(context.Context, *google_protobuf.Empty) (*RepoCredWrapper, error)
	SetRepoCreds(context.Context, *RepoCreds) (*google_protobuf.Empty, error)
	SetK8SCreds(context.Context, *K8SCreds) (*google_protobuf.Empty, error)
	GetK8SCreds(context.Context, *google_protobuf.Empty) (*K8SCredsWrapper, error)
	GetAllCreds(context.Context, *google_protobuf.Empty) (*AllCredsWrapper, error)
	BuildRuntime(context.Context, *BuildQuery) (*Builds, error)
	Logs(*BuildQuery, GuideOcelot_LogsServer) error
	LastFewSummaries(context.Context, *RepoAccount) (*Summaries, error)
	GetStatus(context.Context, *StatusQuery) (*Status, error)
	WatchRepo(context.Context, *RepoAccount) (*google_protobuf.Empty, error)
	BuildRepoAndHash(*BuildReq, GuideOcelot_BuildRepoAndHashServer) error
	PollRepo(context.Context, *PollRequest) (*google_protobuf.Empty, error)
	DeletePollRepo(context.Context, *PollRequest) (*google_protobuf.Empty, error)
	ListPolledRepos(context.Context, *google_protobuf.Empty) (*Polls, error)
	FindWerker(context.Context, *BuildReq) (*BuildRuntimeInfo, error)
}

func RegisterGuideOcelotServer(s *grpc.Server, srv GuideOcelotServer) {
	s.RegisterService(&_GuideOcelot_serviceDesc, srv)
}

func _GuideOcelot_GetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetVCSCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateVCSCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateVCSCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateVCSCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateVCSCreds(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_VCSCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VCSCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).VCSCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/VCSCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).VCSCredExists(ctx, req.(*VCSCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_CheckConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).CheckConn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/CheckConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).CheckConn(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetVCSPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetVCSPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetVCSPrivateKey(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_RepoCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).RepoCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/RepoCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).RepoCredExists(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateK8SCreds(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_K8SCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).K8SCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/K8SCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).K8SCredExists(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_UpdateSSHCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).UpdateSSHCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/UpdateSSHCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).UpdateSSHCreds(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SSHCredExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SSHCredExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SSHCredExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SSHCredExists(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetSSHCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeyWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetSSHCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetSSHCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetSSHCreds(ctx, req.(*SSHKeyWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetSSHCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetSSHCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetSSHCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetSSHCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetRepoCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetRepoCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetRepoCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetRepoCreds(ctx, req.(*RepoCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_SetK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(K8SCreds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).SetK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/SetK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).SetK8SCreds(ctx, req.(*K8SCreds))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetK8SCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetK8SCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetK8SCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetK8SCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetAllCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetAllCreds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetAllCreds(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/BuildRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).BuildRuntime(ctx, req.(*BuildQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).Logs(m, &guideOcelotLogsServer{stream})
}

type GuideOcelot_LogsServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotLogsServer struct {
	grpc.ServerStream
}

func (x *guideOcelotLogsServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_LastFewSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/LastFewSummaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).LastFewSummaries(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).GetStatus(ctx, req.(*StatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_WatchRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).WatchRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/WatchRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).WatchRepo(ctx, req.(*RepoAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_BuildRepoAndHash_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuideOcelotServer).BuildRepoAndHash(m, &guideOcelotBuildRepoAndHashServer{stream})
}

type GuideOcelot_BuildRepoAndHashServer interface {
	Send(*LineResponse) error
	grpc.ServerStream
}

type guideOcelotBuildRepoAndHashServer struct {
	grpc.ServerStream
}

func (x *guideOcelotBuildRepoAndHashServer) Send(m *LineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuideOcelot_PollRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).PollRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/PollRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).PollRepo(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_DeletePollRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).DeletePollRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/DeletePollRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).DeletePollRepo(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_ListPolledRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).ListPolledRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/ListPolledRepos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).ListPolledRepos(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideOcelot_FindWerker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideOcelotServer).FindWerker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.GuideOcelot/FindWerker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideOcelotServer).FindWerker(ctx, req.(*BuildReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuideOcelot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.GuideOcelot",
	HandlerType: (*GuideOcelotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVCSCreds",
			Handler:    _GuideOcelot_GetVCSCreds_Handler,
		},
		{
			MethodName: "SetVCSCreds",
			Handler:    _GuideOcelot_SetVCSCreds_Handler,
		},
		{
			MethodName: "UpdateVCSCreds",
			Handler:    _GuideOcelot_UpdateVCSCreds_Handler,
		},
		{
			MethodName: "VCSCredExists",
			Handler:    _GuideOcelot_VCSCredExists_Handler,
		},
		{
			MethodName: "CheckConn",
			Handler:    _GuideOcelot_CheckConn_Handler,
		},
		{
			MethodName: "SetVCSPrivateKey",
			Handler:    _GuideOcelot_SetVCSPrivateKey_Handler,
		},
		{
			MethodName: "UpdateRepoCreds",
			Handler:    _GuideOcelot_UpdateRepoCreds_Handler,
		},
		{
			MethodName: "RepoCredExists",
			Handler:    _GuideOcelot_RepoCredExists_Handler,
		},
		{
			MethodName: "UpdateK8SCreds",
			Handler:    _GuideOcelot_UpdateK8SCreds_Handler,
		},
		{
			MethodName: "K8SCredExists",
			Handler:    _GuideOcelot_K8SCredExists_Handler,
		},
		{
			MethodName: "UpdateSSHCreds",
			Handler:    _GuideOcelot_UpdateSSHCreds_Handler,
		},
		{
			MethodName: "SSHCredExists",
			Handler:    _GuideOcelot_SSHCredExists_Handler,
		},
		{
			MethodName: "SetSSHCreds",
			Handler:    _GuideOcelot_SetSSHCreds_Handler,
		},
		{
			MethodName: "GetSSHCreds",
			Handler:    _GuideOcelot_GetSSHCreds_Handler,
		},
		{
			MethodName: "GetRepoCreds",
			Handler:    _GuideOcelot_GetRepoCreds_Handler,
		},
		{
			MethodName: "SetRepoCreds",
			Handler:    _GuideOcelot_SetRepoCreds_Handler,
		},
		{
			MethodName: "SetK8SCreds",
			Handler:    _GuideOcelot_SetK8SCreds_Handler,
		},
		{
			MethodName: "GetK8SCreds",
			Handler:    _GuideOcelot_GetK8SCreds_Handler,
		},
		{
			MethodName: "GetAllCreds",
			Handler:    _GuideOcelot_GetAllCreds_Handler,
		},
		{
			MethodName: "BuildRuntime",
			Handler:    _GuideOcelot_BuildRuntime_Handler,
		},
		{
			MethodName: "LastFewSummaries",
			Handler:    _GuideOcelot_LastFewSummaries_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _GuideOcelot_GetStatus_Handler,
		},
		{
			MethodName: "WatchRepo",
			Handler:    _GuideOcelot_WatchRepo_Handler,
		},
		{
			MethodName: "PollRepo",
			Handler:    _GuideOcelot_PollRepo_Handler,
		},
		{
			MethodName: "DeletePollRepo",
			Handler:    _GuideOcelot_DeletePollRepo_Handler,
		},
		{
			MethodName: "ListPolledRepos",
			Handler:    _GuideOcelot_ListPolledRepos_Handler,
		},
		{
			MethodName: "FindWerker",
			Handler:    _GuideOcelot_FindWerker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _GuideOcelot_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildRepoAndHash",
			Handler:       _GuideOcelot_BuildRepoAndHash_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "guideocelot.proto",
}

func init() { proto.RegisterFile("guideocelot.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 3189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xcb, 0x6f, 0x23, 0xc7,
	0x99, 0x77, 0x53, 0x12, 0x45, 0x15, 0xf5, 0xe0, 0xf4, 0x8c, 0xc7, 0xda, 0xde, 0xc5, 0x6e, 0xa1,
	0xd7, 0x5e, 0x8c, 0xc7, 0x1a, 0x6a, 0x46, 0x6b, 0x63, 0xe5, 0x31, 0xbc, 0xbb, 0x1c, 0x5a, 0x33,
	0x12, 0x24, 0xcf, 0x83, 0x94, 0xc6, 0xfb, 0xf4, 0xba, 0xd9, 0xfc, 0x48, 0xb6, 0xd9, 0xec, 0xee,
	0xa9, 0xaa, 0x16, 0x4d, 0xac, 0xb1, 0x07, 0x1b, 0xb6, 0x2f, 0xfb, 0xc0, 0x72, 0x0f, 0x8b, 0xe4,
	0x92, 0x5c, 0x9c, 0x9c, 0x02, 0x03, 0x49, 0x90, 0xc7, 0x25, 0xe7, 0x20, 0x57, 0x03, 0x01, 0x72,
	0x4e, 0x2e, 0x01, 0xf2, 0xfc, 0x0f, 0x82, 0xaf, 0x1e, 0xcd, 0x26, 0x25, 0x66, 0x3c, 0x03, 0xf8,
	0xc4, 0xae, 0xd7, 0x57, 0xbf, 0xef, 0xf7, 0x3d, 0xea, 0xab, 0x22, 0xb9, 0xd0, 0x4d, 0x83, 0x36,
	0xc4, 0x3e, 0x84, 0xb1, 0xa8, 0x26, 0x2c, 0x16, 0xb1, 0x5d, 0x1c, 0xc4, 0x6d, 0x08, 0xb9, 0xf3,
	0xa7, 0xdd, 0x38, 0xee, 0x86, 0xb0, 0x2d, 0x7b, 0x5b, 0x69, 0x67, 0x1b, 0x06, 0x89, 0x18, 0xa9,
	0x49, 0xce, 0x9f, 0xe9, 0x41, 0x2f, 0x09, 0xb6, 0xbd, 0x28, 0x8a, 0x85, 0x27, 0x82, 0x38, 0xe2,
	0x7a, 0xf4, 0x2f, 0x66, 0x97, 0x8a, 0x60, 0x00, 0x5c, 0x78, 0x83, 0x44, 0x4f, 0xd8, 0x92, 0x3f,
	0xfe, 0xb5, 0x2e, 0x44, 0xd7, 0xf8, 0xd0, 0xeb, 0x76, 0x81, 0x6d, 0xc7, 0x89, 0x14, 0x71, 0x56,
	0x9c, 0xdb, 0x20, 0xa5, 0x5b, 0x69, 0x10, 0xb6, 0x1b, 0xf0, 0xc8, 0x76, 0x48, 0xc9, 0xf3, 0x7d,
	0xd1, 0x80, 0x24, 0xde, 0xb4, 0xa8, 0x75, 0x65, 0xa5, 0x91, 0xb5, 0x6d, 0x9b, 0x2c, 0xf6, 0x3c,
	0xde, 0xdb, 0x2c, 0xc8, 0x7e, 0xf9, 0x6d, 0x5f, 0x26, 0xc5, 0x16, 0xf3, 0x22, 0xbf, 0xb7, 0xb9,
	0x20, 0x7b, 0x75, 0xcb, 0x1d, 0x91, 0x8d, 0x5a, 0x18, 0xd6, 0x19, 0xb4, 0xf9, 0x5b, 0xcc, 0x4b,
	0x12, 0x60, 0xf6, 0x2b, 0x64, 0x85, 0x41, 0x12, 0xcb, 0x3e, 0x29, 0xbb, 0xbc, 0xf3, 0x5c, 0x55,
	0x91, 0x51, 0x6d, 0xe8, 0x01, 0x3d, 0xb7, 0x31, 0x99, 0x69, 0x6f, 0x93, 0xd2, 0xa9, 0xcf, 0xd5,
	0xaa, 0x05, 0xb9, 0xea, 0xa2, 0x59, 0x95, 0x5f, 0x91, 0x4d, 0x72, 0x6f, 0x90, 0x72, 0x6e, 0xc0,
	0x76, 0xc9, 0xc2, 0xa9, 0xcf, 0x37, 0x0b, 0x74, 0xe1, 0x4a, 0x79, 0xa7, 0x62, 0x96, 0x3e, 0xac,
	0x37, 0xe5, 0xec, 0x06, 0x0e, 0xba, 0x5f, 0xb5, 0xc8, 0x5a, 0xb3, 0xb9, 0x7f, 0x08, 0x23, 0xb3,
	0x4a, 0xf3, 0x70, 0xd7, 0x1b, 0x40, 0x9e, 0x07, 0x6c, 0xdb, 0x7f, 0x4e, 0x48, 0xc2, 0x82, 0x53,
	0x4f, 0xc0, 0x21, 0x8c, 0x24, 0x1b, 0xab, 0x8d, 0x5c, 0x8f, 0x7d, 0x8d, 0x2c, 0xf3, 0xb4, 0x75,
	0x3c, 0x4a, 0x60, 0x93, 0x50, 0xeb, 0xca, 0xfa, 0x04, 0x70, 0x33, 0x6d, 0xe1, 0xae, 0x38, 0xd4,
	0x30, 0x73, 0x50, 0x5c, 0xd0, 0x86, 0x48, 0x04, 0x9d, 0x00, 0xd8, 0x66, 0x59, 0x6e, 0x96, 0xeb,
	0x71, 0x5f, 0x26, 0xcb, 0xcd, 0xe6, 0x3e, 0x02, 0xb3, 0x5f, 0x24, 0x8b, 0x7d, 0x18, 0x21, 0x7b,
	0xa8, 0xcc, 0xb3, 0x99, 0xd8, 0x3c, 0xf4, 0x86, 0x9c, 0xe2, 0xfe, 0xde, 0x22, 0x25, 0xa3, 0x24,
	0x6a, 0xe3, 0x87, 0x01, 0x44, 0xe2, 0xa0, 0x6d, 0xb4, 0x31, 0x6d, 0xdb, 0x25, 0xab, 0xea, 0xbb,
	0x09, 0x3e, 0x03, 0xa1, 0xad, 0x3b, 0xd5, 0x37, 0x03, 0xb1, 0x34, 0x0b, 0x11, 0xe5, 0x8b, 0xb8,
	0x0f, 0xd1, 0x49, 0xe3, 0x48, 0xfb, 0x41, 0xd6, 0x9e, 0x62, 0x72, 0xf1, 0x2c, 0x93, 0x9c, 0xf7,
	0x6e, 0x07, 0x21, 0x1c, 0xc5, 0xfe, 0x66, 0x51, 0xc9, 0x9d, 0xf4, 0x3c, 0x21, 0x93, 0xee, 0x2e,
	0xd9, 0x98, 0x71, 0x24, 0xfb, 0x05, 0xb2, 0x88, 0xae, 0xb4, 0xb9, 0x20, 0x19, 0xbb, 0x30, 0xeb,
	0x6f, 0xbc, 0x21, 0x87, 0xdd, 0x1f, 0x5b, 0x64, 0x25, 0xeb, 0x43, 0xc8, 0x29, 0x07, 0x16, 0xe5,
	0x8c, 0x6f, 0xda, 0x38, 0x96, 0x78, 0x9c, 0x0f, 0x63, 0xd6, 0xd6, 0x54, 0x65, 0x6d, 0x7b, 0x93,
	0x2c, 0xa3, 0xb4, 0x13, 0x16, 0x6a, 0x5d, 0x4c, 0xf3, 0x8b, 0x10, 0x38, 0x97, 0xa4, 0x27, 0x24,
	0xe1, 0xff, 0x2d, 0x52, 0x3a, 0xdc, 0x9d, 0x18, 0x7e, 0xae, 0x1b, 0x53, 0x52, 0xee, 0xef, 0xf2,
	0x7a, 0x1c, 0x09, 0x88, 0x04, 0xd7, 0xca, 0xe4, 0xbb, 0x66, 0x50, 0x2f, 0x9c, 0x41, 0x9d, 0x43,
	0xb6, 0xf4, 0x05, 0x90, 0xfd, 0x1d, 0xd9, 0x30, 0xc0, 0x8c, 0x79, 0xb6, 0x26, 0x58, 0x67, 0x23,
	0xd4, 0xf4, 0x37, 0xb2, 0x19, 0xee, 0xbf, 0x93, 0x72, 0x53, 0x78, 0x22, 0xe5, 0x0f, 0x52, 0x60,
	0xa3, 0x2c, 0x1f, 0x59, 0xb9, 0x7c, 0x94, 0x57, 0xb8, 0x30, 0xa3, 0xb0, 0x43, 0x4a, 0x68, 0x0f,
	0x39, 0xa6, 0xbd, 0xd4, 0xb4, 0x91, 0x8c, 0xc4, 0x63, 0x22, 0xf0, 0x42, 0x99, 0xfa, 0x94, 0x0d,
	0xf2, 0x5d, 0xee, 0x4d, 0x42, 0x64, 0x96, 0x9c, 0xbf, 0xf7, 0x26, 0x59, 0x6e, 0xe1, 0x8c, 0x03,
	0xe5, 0x19, 0x0b, 0x0d, 0xd3, 0x74, 0xff, 0xd7, 0x22, 0x45, 0xb9, 0x98, 0xdb, 0x3b, 0xa4, 0x28,
	0x7b, 0x4d, 0x10, 0x3b, 0x46, 0x5f, 0x35, 0xae, 0x7f, 0xf6, 0x22, 0xc1, 0x46, 0x0d, 0x3d, 0xd3,
	0x69, 0x92, 0x72, 0xae, 0xdb, 0xae, 0x90, 0x85, 0x3e, 0x8c, 0xf4, 0xd6, 0xf8, 0x69, 0x57, 0xc9,
	0xd2, 0xa9, 0x17, 0xa6, 0x4a, 0xe5, 0xf2, 0xce, 0xe6, 0x94, 0xcc, 0x46, 0x1a, 0xe1, 0xf9, 0x70,
	0x10, 0x75, 0xe2, 0x86, 0x9a, 0x76, 0xb3, 0xb0, 0x6b, 0xb9, 0xdf, 0xb3, 0x48, 0x65, 0x76, 0x1c,
	0xd5, 0x6a, 0xc7, 0x91, 0xf2, 0x95, 0x52, 0x43, 0x7e, 0xdb, 0xeb, 0xa4, 0x10, 0x24, 0x9a, 0xcc,
	0x42, 0x90, 0x20, 0x8d, 0x5d, 0x96, 0xf8, 0xf7, 0x63, 0x26, 0x0c, 0x8d, 0xa6, 0x9d, 0xd1, 0xb2,
	0x38, 0xc7, 0x24, 0x4b, 0x7f, 0xc4, 0x24, 0xc5, 0x19, 0x93, 0x5c, 0x26, 0xc5, 0x21, 0x97, 0xbb,
	0x2c, 0xab, 0xa3, 0x45, 0xb5, 0xdc, 0x2a, 0x59, 0x3d, 0x0a, 0x22, 0x68, 0x00, 0x4f, 0xe2, 0x88,
	0xcb, 0x24, 0x12, 0xa7, 0x22, 0x49, 0x05, 0xf6, 0x6a, 0x56, 0x72, 0x3d, 0xee, 0x03, 0x52, 0x46,
	0x03, 0xd6, 0x7c, 0x3f, 0x4e, 0x23, 0x09, 0x91, 0x4d, 0x4e, 0x37, 0xf9, 0x8d, 0x96, 0xf3, 0xd4,
	0xb0, 0xd6, 0xd3, 0x34, 0xed, 0x4b, 0x64, 0x29, 0x0c, 0x06, 0x81, 0xd2, 0x74, 0xa9, 0xa1, 0x1a,
	0xee, 0x27, 0x16, 0x29, 0x2a, 0x4f, 0xb4, 0xaf, 0x93, 0x92, 0xb4, 0x52, 0x33, 0x1d, 0xe8, 0x43,
	0xed, 0xd2, 0x14, 0xfb, 0xcd, 0x74, 0x30, 0xf0, 0xd8, 0xa8, 0x91, 0xcd, 0xb2, 0x5f, 0x22, 0x45,
	0x2e, 0xbc, 0x2e, 0x18, 0x8f, 0x9f, 0x04, 0x0d, 0xf6, 0x2a, 0xb1, 0x0d, 0x3d, 0x45, 0x86, 0x20,
	0x3f, 0x88, 0xea, 0x71, 0xc4, 0xd3, 0x50, 0x82, 0x28, 0x35, 0x72, 0x3d, 0xee, 0xcf, 0x2c, 0x19,
	0x13, 0x66, 0x1d, 0xfa, 0x71, 0xae, 0xa9, 0x95, 0x9c, 0x9a, 0x71, 0x89, 0x2c, 0x01, 0x63, 0x31,
	0xd3, 0x9a, 0xaa, 0x06, 0x92, 0xcd, 0xd5, 0x12, 0xa5, 0xa8, 0x6e, 0xa1, 0x81, 0x06, 0xc0, 0xb9,
	0x84, 0xbb, 0x48, 0x17, 0xd0, 0x40, 0xa6, 0x6d, 0xef, 0x92, 0x15, 0x2e, 0x3c, 0x26, 0x8e, 0x03,
	0x6d, 0x59, 0xf4, 0x66, 0x55, 0x9a, 0x54, 0x4d, 0x69, 0x52, 0x3d, 0x36, 0xa5, 0x49, 0x63, 0x32,
	0xd9, 0x7e, 0x9e, 0xac, 0x49, 0xfd, 0xde, 0x48, 0x99, 0xac, 0x44, 0xa4, 0xed, 0xad, 0xc6, 0x74,
	0xa7, 0xfb, 0xdd, 0x02, 0x59, 0xcd, 0x73, 0x78, 0x6e, 0xd0, 0x5d, 0x26, 0xc5, 0x8e, 0x17, 0x84,
	0xa0, 0x62, 0xae, 0xd4, 0xd0, 0x2d, 0x04, 0x27, 0x19, 0x97, 0xe0, 0x16, 0x1e, 0x0f, 0x2e, 0x9b,
	0x9c, 0x77, 0x86, 0xc5, 0x69, 0x67, 0x78, 0x9e, 0xac, 0xc9, 0x69, 0x19, 0xec, 0x25, 0x05, 0x7b,
	0xaa, 0x33, 0x73, 0xb0, 0x62, 0xce, 0xc1, 0x26, 0x65, 0xd2, 0x72, 0xbe, 0x4c, 0xca, 0xa7, 0x8c,
	0xd2, 0x54, 0xca, 0x40, 0xfc, 0x8f, 0x52, 0x48, 0x41, 0xe2, 0x5f, 0x79, 0x3c, 0xfe, 0x6c, 0xb2,
	0xfb, 0x0a, 0x59, 0x51, 0x84, 0x05, 0xc0, 0xed, 0x2b, 0x64, 0x91, 0xa7, 0x03, 0x93, 0x6c, 0xce,
	0x77, 0x4d, 0x39, 0xc3, 0xfd, 0xac, 0x40, 0xca, 0xf7, 0xe3, 0x30, 0x6c, 0xc0, 0xa3, 0x14, 0xb8,
	0xc8, 0xd3, 0x60, 0x4d, 0xd3, 0x60, 0x14, 0x2c, 0xe4, 0x14, 0xb4, 0xc9, 0xa2, 0xcf, 0xe2, 0xc8,
	0x04, 0x3e, 0x7e, 0xa3, 0xef, 0x28, 0x35, 0x81, 0x9b, 0xc0, 0x37, 0x6d, 0xfb, 0x6f, 0xc9, 0x6a,
	0xe8, 0x71, 0x51, 0x67, 0x71, 0x24, 0x35, 0x2c, 0x3e, 0x56, 0xc3, 0xa9, 0xf9, 0x76, 0x9d, 0x10,
	0x6c, 0xef, 0x7b, 0x1c, 0xa5, 0x2f, 0x4b, 0xed, 0xfe, 0xd2, 0x68, 0x97, 0x53, 0xa3, 0x7a, 0x94,
	0xcd, 0x52, 0x39, 0x35, 0xb7, 0xcc, 0x79, 0x9d, 0x6c, 0xcc, 0x0c, 0x9f, 0x93, 0x5b, 0x2f, 0xe5,
	0x73, 0xeb, 0x4a, 0x3e, 0x83, 0xee, 0x90, 0x25, 0xdc, 0x89, 0xdb, 0x2f, 0x92, 0xa5, 0x04, 0x3f,
	0x34, 0xcb, 0x17, 0xcf, 0xc1, 0xd1, 0x50, 0x33, 0x5c, 0x4a, 0x8a, 0x7b, 0xef, 0x05, 0x5c, 0x70,
	0x74, 0x09, 0x90, 0x5f, 0x3a, 0xd9, 0xea, 0xd6, 0xd5, 0xd7, 0x48, 0xc9, 0x1c, 0x9d, 0x36, 0x21,
	0xc5, 0xbb, 0x07, 0x47, 0xff, 0x56, 0x3f, 0xae, 0x3c, 0x63, 0x2f, 0x93, 0x85, 0x87, 0xf5, 0x66,
	0xc5, 0xb2, 0x4b, 0x64, 0xb1, 0xb1, 0x77, 0xff, 0x5e, 0xa5, 0x80, 0x5d, 0x87, 0xbb, 0xcd, 0xca,
	0x02, 0x7e, 0x34, 0x9b, 0xfb, 0x95, 0xa5, 0xab, 0x8f, 0x48, 0x39, 0x77, 0xf4, 0xda, 0x65, 0xb2,
	0x8c, 0xeb, 0x9b, 0x52, 0xc0, 0x1a, 0x59, 0xb9, 0x75, 0x70, 0x7c, 0xeb, 0xa4, 0x7e, 0xb8, 0x77,
	0x5c, 0xb1, 0x50, 0xf6, 0x9d, 0x83, 0xe3, 0xfd, 0x93, 0x5b, 0x95, 0x82, 0xbd, 0x42, 0x96, 0xee,
	0xee, 0xfd, 0xc3, 0x09, 0x8a, 0x5a, 0x21, 0x4b, 0x6f, 0xd6, 0x1e, 0xee, 0xdd, 0xad, 0x2c, 0xe2,
	0x8c, 0x37, 0xee, 0xd5, 0x0f, 0xf7, 0x1a, 0x95, 0x25, 0x7b, 0x95, 0x94, 0x0e, 0x4f, 0x6e, 0xed,
	0xd5, 0xef, 0xdd, 0xbd, 0x5d, 0x29, 0xe2, 0x08, 0xd6, 0x9c, 0x7b, 0xff, 0x58, 0x29, 0xed, 0x7c,
	0xfb, 0xaf, 0x48, 0xf9, 0x0e, 0xde, 0x72, 0xee, 0xc9, 0x5b, 0x8e, 0xfd, 0x4d, 0x8b, 0x94, 0xef,
	0x80, 0xc8, 0x6a, 0xcf, 0xcb, 0x67, 0x6c, 0xba, 0x87, 0x17, 0x1d, 0xe7, 0xbc, 0x2a, 0xde, 0xed,
	0x8f, 0x6b, 0x4d, 0xe7, 0x41, 0x03, 0x44, 0xca, 0x22, 0x4e, 0xbd, 0x30, 0xa4, 0x0f, 0xeb, 0x4d,
	0xea, 0xa3, 0x20, 0x2a, 0x7a, 0x9e, 0xa0, 0xea, 0x2a, 0x45, 0x7b, 0x1e, 0xa7, 0x5e, 0xd4, 0xa6,
	0xbe, 0x17, 0xd1, 0x94, 0x03, 0xed, 0xc4, 0x8c, 0xfa, 0x3d, 0xf0, 0xfb, 0x41, 0xd4, 0xa5, 0x71,
	0x2a, 0xa8, 0x1f, 0xb7, 0x81, 0x8a, 0x98, 0xca, 0x70, 0xaa, 0x7e, 0xf0, 0xf9, 0x2f, 0xfe, 0xaf,
	0xb0, 0x61, 0xaf, 0x6d, 0x9f, 0xde, 0xd8, 0x96, 0xc2, 0xb6, 0x4f, 0x7d, 0x6e, 0x7f, 0x05, 0x73,
	0x67, 0x0e, 0xe9, 0x99, 0xcb, 0x81, 0x33, 0x07, 0xbb, 0xfb, 0xce, 0xb8, 0xb6, 0xe7, 0xd4, 0x6b,
	0xed, 0x36, 0xf5, 0x68, 0x04, 0xc3, 0x0c, 0x24, 0x56, 0x46, 0x5e, 0x48, 0xfd, 0x38, 0xea, 0x04,
	0x5d, 0x9d, 0x0f, 0x10, 0x85, 0x46, 0x2d, 0x51, 0x22, 0x30, 0x09, 0x35, 0x4e, 0x85, 0x02, 0x66,
	0xbb, 0xd3, 0xc0, 0x6e, 0x5a, 0x57, 0xed, 0x84, 0xac, 0x9f, 0x24, 0x6d, 0x4f, 0xc0, 0x53, 0xa0,
	0x7b, 0x79, 0x5c, 0xfb, 0x13, 0xe7, 0x39, 0xb5, 0x9c, 0x7a, 0x12, 0x5c, 0x3d, 0x03, 0xa7, 0x76,
	0x74, 0xce, 0xee, 0xf8, 0x99, 0x45, 0xd6, 0xb4, 0x68, 0xed, 0xa1, 0x67, 0x77, 0x5c, 0x37, 0x3d,
	0x6a, 0x86, 0xfb, 0xfe, 0xb8, 0xf6, 0xaf, 0xce, 0x3f, 0xd7, 0x51, 0x1b, 0x1a, 0x74, 0x66, 0x76,
	0xa2, 0xca, 0xa1, 0x69, 0x10, 0x19, 0xfd, 0xbd, 0x90, 0x81, 0xd7, 0x1e, 0x55, 0xe9, 0xed, 0x98,
	0xd1, 0x7e, 0x14, 0x0f, 0xd1, 0x5a, 0xc3, 0x1e, 0x88, 0x1e, 0x30, 0xa4, 0xc9, 0x47, 0x83, 0x6b,
	0xdc, 0x31, 0xa3, 0x4d, 0x10, 0x12, 0xed, 0x65, 0xfb, 0xd2, 0x14, 0xda, 0x6d, 0x25, 0xd8, 0x7e,
	0x9d, 0xac, 0xc8, 0xad, 0xeb, 0x71, 0x14, 0xcd, 0x75, 0xb3, 0x79, 0x24, 0x3d, 0x63, 0xff, 0xd2,
	0x22, 0x15, 0x65, 0xfe, 0xfb, 0x93, 0xbb, 0xdb, 0xf9, 0x77, 0xaa, 0xb9, 0x52, 0x3e, 0xb5, 0xc6,
	0xb5, 0x8f, 0x2c, 0xe7, 0x03, 0xab, 0x26, 0x84, 0xe7, 0xf7, 0xa8, 0xe8, 0x01, 0x5a, 0x5f, 0x96,
	0xcf, 0x34, 0xee, 0x50, 0x2f, 0xa2, 0x9c, 0xf7, 0x68, 0x27, 0x08, 0xa5, 0x37, 0x7a, 0xf4, 0xd4,
	0xe7, 0x54, 0xe7, 0xd1, 0x2a, 0x3d, 0xee, 0x05, 0x5c, 0x8d, 0x0d, 0x83, 0x30, 0xa4, 0x2d, 0xa0,
	0x9e, 0x14, 0x03, 0x6d, 0x9c, 0x8c, 0xb2, 0xa4, 0xfb, 0x4a, 0x89, 0x5e, 0x10, 0x01, 0x53, 0x1e,
	0x14, 0xc6, 0x11, 0x12, 0x87, 0xe3, 0x98, 0x7b, 0x79, 0x20, 0x62, 0x36, 0x52, 0xae, 0x74, 0xd9,
	0xbd, 0x30, 0x4d, 0x15, 0xe7, 0x3d, 0x34, 0xee, 0xa7, 0x16, 0xd9, 0x50, 0xc4, 0x4e, 0x6e, 0x39,
	0x67, 0x2f, 0x43, 0x73, 0xd5, 0xec, 0x8e, 0x6b, 0x87, 0xce, 0x81, 0xb6, 0x0c, 0x3a, 0xfc, 0x17,
	0x74, 0xf6, 0x09, 0x3c, 0x1a, 0x44, 0x02, 0xba, 0x6a, 0x92, 0x82, 0x7a, 0xd1, 0x59, 0x9f, 0x40,
	0xc5, 0x89, 0x88, 0xf3, 0x3b, 0x16, 0x59, 0x37, 0x70, 0xb4, 0x17, 0x9e, 0x03, 0x73, 0xd6, 0x0d,
	0xff, 0x63, 0x5c, 0x7b, 0xdb, 0xf9, 0x97, 0xcc, 0x0d, 0x71, 0xe2, 0x97, 0xe1, 0x87, 0xcf, 0xd9,
	0xcf, 0x4e, 0x23, 0x36, 0x8e, 0x38, 0xb6, 0x4c, 0xb4, 0x66, 0x17, 0xaf, 0x33, 0xd7, 0x98, 0xb9,
	0xdc, 0x3e, 0x1c, 0xd7, 0x5e, 0x73, 0x5e, 0xcd, 0xa2, 0xb5, 0x9f, 0xb6, 0x40, 0x51, 0x9a, 0x03,
	0x8c, 0x5c, 0xe2, 0x00, 0x8b, 0x40, 0x00, 0x3f, 0xcb, 0xe5, 0x54, 0x3c, 0xf7, 0x77, 0x65, 0x3c,
	0x7f, 0xdf, 0x22, 0x6b, 0x7a, 0xf3, 0xd9, 0x78, 0xce, 0x30, 0xcd, 0x12, 0xf9, 0xa1, 0x35, 0xae,
	0xb5, 0x9d, 0x56, 0xc6, 0x64, 0x0e, 0xcc, 0x97, 0x1d, 0xd7, 0xfd, 0xdd, 0x2c, 0xae, 0x3f, 0xc9,
	0xe8, 0x6c, 0x36, 0xf7, 0x15, 0x9d, 0x4f, 0x18, 0x96, 0xb7, 0xc7, 0xb5, 0x97, 0x9c, 0x17, 0x33,
	0x4e, 0x31, 0x04, 0xfb, 0x30, 0x92, 0x34, 0xe2, 0x69, 0x11, 0x44, 0x3a, 0xb0, 0xb8, 0xcf, 0x82,
	0x44, 0xf0, 0xb3, 0x1c, 0xea, 0xb0, 0xf9, 0x91, 0x7a, 0x17, 0xca, 0x71, 0x38, 0x07, 0xc8, 0x2c,
	0x91, 0x1f, 0x59, 0xe3, 0x5a, 0xc7, 0x69, 0x67, 0x44, 0x66, 0x08, 0x30, 0xd8, 0xbf, 0x6c, 0x2a,
	0x39, 0xef, 0x19, 0x2a, 0xbf, 0xae, 0x8e, 0xb8, 0xa7, 0xe5, 0xb1, 0x35, 0xae, 0xdd, 0x71, 0xf6,
	0x26, 0xe7, 0x9c, 0x51, 0x03, 0x53, 0x59, 0x64, 0xf2, 0x18, 0xe5, 0xfa, 0x98, 0xe5, 0xf2, 0x38,
	0xf6, 0x7c, 0x1f, 0x38, 0x9e, 0xd6, 0x30, 0xa0, 0x9e, 0xa0, 0x4c, 0xdd, 0x2e, 0xcf, 0x39, 0xe9,
	0x34, 0xc7, 0x6f, 0xca, 0x72, 0x21, 0x43, 0x38, 0x2f, 0x8f, 0x6f, 0xe4, 0x90, 0x23, 0x6c, 0xf7,
	0xd9, 0xb3, 0x87, 0x3a, 0xe7, 0x3d, 0x74, 0x9e, 0xd5, 0x3b, 0x20, 0x26, 0x69, 0x6e, 0x9e, 0xc0,
	0x79, 0x6f, 0x8f, 0xe8, 0x3c, 0xd7, 0x9c, 0x97, 0xee, 0x80, 0x90, 0xf5, 0x07, 0xda, 0x20, 0x92,
	0x89, 0x2c, 0x1f, 0x76, 0xb9, 0x04, 0xc8, 0x95, 0x6a, 0x15, 0x7b, 0x26, 0x9d, 0xd9, 0x3f, 0xb1,
	0xc8, 0x6a, 0x33, 0x8f, 0xe4, 0x09, 0x12, 0xee, 0x7f, 0x5b, 0xe3, 0x1a, 0x73, 0x12, 0x64, 0x1e,
	0x79, 0x97, 0xdb, 0x4f, 0xb6, 0xac, 0x52, 0xf3, 0xe4, 0xb4, 0x45, 0xf5, 0x0b, 0xd3, 0x16, 0x35,
	0x77, 0xea, 0x2d, 0x6a, 0xde, 0xaa, 0x64, 0x85, 0x24, 0x46, 0x09, 0x50, 0x8f, 0xe1, 0x51, 0xf1,
	0x28, 0x0d, 0x18, 0xb4, 0xab, 0xaa, 0x6b, 0x90, 0x72, 0x81, 0x27, 0x4e, 0x04, 0xef, 0xa5, 0xfc,
	0xfd, 0x76, 0xec, 0xf7, 0x81, 0xe9, 0xc4, 0xec, 0x9e, 0x93, 0x98, 0x1f, 0x48, 0x3f, 0x7a, 0x8a,
	0xf4, 0xb6, 0x79, 0xd6, 0xf0, 0x3a, 0x41, 0x9d, 0x48, 0xc3, 0x67, 0x22, 0x1f, 0x6b, 0xa7, 0x99,
	0xb7, 0xa3, 0xf3, 0x1c, 0xa0, 0xbf, 0xcb, 0x11, 0xe9, 0x1d, 0x10, 0xe6, 0xf1, 0xf9, 0xf1, 0x62,
	0x67, 0x9e, 0xa9, 0xdd, 0x0b, 0x52, 0x6c, 0xd9, 0x5e, 0xc9, 0xc4, 0xda, 0x47, 0xfa, 0x1e, 0xaa,
	0x5f, 0x4a, 0x6c, 0x7b, 0xea, 0x1a, 0x25, 0x1f, 0x84, 0x26, 0x19, 0x40, 0xbd, 0xd4, 0x18, 0xbd,
	0xed, 0x0a, 0x8a, 0x91, 0xe1, 0xa1, 0x23, 0xc1, 0xfe, 0x41, 0x81, 0x2c, 0x1e, 0xc5, 0x5d, 0x7e,
	0xae, 0x98, 0xec, 0x86, 0x96, 0x7f, 0xe2, 0x70, 0x3f, 0x2c, 0x8c, 0x6b, 0xbf, 0xb5, 0x9c, 0x5f,
	0x59, 0x5d, 0x10, 0x94, 0x0b, 0x06, 0xde, 0x00, 0xab, 0x8b, 0x30, 0xee, 0x72, 0x99, 0xd4, 0x3c,
	0xca, 0x13, 0xf0, 0x83, 0x4e, 0xe0, 0xeb, 0x82, 0x57, 0x46, 0x22, 0x04, 0x32, 0x6b, 0x3c, 0x42,
	0xc1, 0xb4, 0x35, 0xa2, 0xfa, 0x6a, 0x89, 0x79, 0x03, 0xaf, 0xce, 0x5b, 0x98, 0x98, 0x4c, 0x5f,
	0xc0, 0x8d, 0x08, 0x68, 0xd3, 0x40, 0x50, 0xe1, 0xf5, 0x81, 0xd3, 0x84, 0x81, 0x0f, 0x51, 0x1b,
	0x22, 0x1f, 0x68, 0x7c, 0x0a, 0x6a, 0x5d, 0x15, 0xd7, 0xe1, 0xc7, 0xf4, 0x22, 0xe9, 0x6c, 0x3d,
	0x60, 0xca, 0xdb, 0x06, 0x69, 0x28, 0x82, 0x24, 0x04, 0x93, 0x19, 0x86, 0x81, 0x50, 0xd5, 0x11,
	0x47, 0xc7, 0xd4, 0xdb, 0x0b, 0x1a, 0x0c, 0xc3, 0xd0, 0x28, 0x84, 0xa3, 0xa1, 0x27, 0x80, 0x0b,
	0x1a, 0x47, 0x50, 0xa5, 0x92, 0x40, 0x62, 0x97, 0x90, 0x40, 0xd4, 0xf4, 0xba, 0x65, 0xff, 0xdc,
	0x22, 0x15, 0xbc, 0xb1, 0xdd, 0x86, 0xe1, 0xe4, 0x8a, 0x7b, 0x31, 0x1f, 0x56, 0xfa, 0x95, 0xc7,
	0xb9, 0x30, 0x79, 0x89, 0xd4, 0xf3, 0xdc, 0x6f, 0x58, 0xe3, 0xda, 0xff, 0x58, 0xce, 0x7f, 0x5a,
	0xb2, 0xd8, 0x62, 0xf2, 0x8e, 0x41, 0xb9, 0x19, 0x46, 0x3e, 0xb3, 0x8a, 0x4b, 0xb1, 0xaa, 0x8a,
	0x39, 0xc6, 0xa4, 0x15, 0xda, 0x98, 0x88, 0xe5, 0xa1, 0x9f, 0x95, 0x6f, 0xf2, 0x2d, 0x48, 0x95,
	0x6e, 0x1c, 0x04, 0xed, 0xc5, 0x43, 0x3a, 0xf0, 0xa2, 0x11, 0x85, 0x48, 0x48, 0x89, 0xa6, 0xa8,
	0x53, 0x5b, 0x41, 0x7b, 0x4b, 0xf5, 0xb4, 0xa1, 0xe3, 0xa5, 0xa1, 0xc0, 0x24, 0xfa, 0x8a, 0x8a,
	0xb8, 0x35, 0xbb, 0x8c, 0x4a, 0x72, 0xfd, 0xcc, 0xf1, 0xc3, 0x05, 0xb2, 0x82, 0x29, 0x51, 0xbd,
	0xc0, 0xe4, 0x9f, 0x87, 0xcc, 0xd3, 0xe7, 0xc4, 0xdb, 0x54, 0xa7, 0xfb, 0xf1, 0xc2, 0xb8, 0xf6,
	0xbb, 0x82, 0xf3, 0xeb, 0x42, 0xb6, 0x8e, 0xe6, 0xb5, 0x94, 0xc4, 0xab, 0x6e, 0x2c, 0x4a, 0xcf,
	0x78, 0xcb, 0x7e, 0x00, 0xcc, 0x63, 0x7e, 0x4f, 0x1d, 0x91, 0x3a, 0xc3, 0x87, 0x71, 0xdc, 0x4f,
	0x13, 0x69, 0xb9, 0x9b, 0x99, 0xc9, 0x79, 0x9a, 0x24, 0x61, 0x90, 0xe9, 0x12, 0x47, 0xe1, 0x88,
	0x72, 0xc0, 0xb5, 0xe8, 0x61, 0xca, 0x3d, 0x0e, 0x3a, 0x59, 0x32, 0x92, 0x5e, 0x61, 0x5e, 0xf4,
	0xa4, 0x63, 0x18, 0x01, 0x72, 0x24, 0x52, 0x57, 0xb9, 0xde, 0x16, 0x25, 0x86, 0xc9, 0x16, 0x60,
	0xfe, 0x6a, 0x53, 0xbc, 0xe0, 0x65, 0x87, 0x36, 0x42, 0x41, 0xfe, 0xd3, 0x44, 0xab, 0x21, 0x37,
	0x91, 0x9b, 0xe7, 0x9e, 0x68, 0xd1, 0x1f, 0xbb, 0xc1, 0x29, 0x44, 0x78, 0x9e, 0xaa, 0xea, 0x58,
	0xde, 0xbd, 0xb7, 0xcc, 0xe1, 0x2a, 0x37, 0xf0, 0x84, 0x80, 0x41, 0x22, 0xe9, 0xef, 0x04, 0x11,
	0x9e, 0x6c, 0x03, 0x4f, 0xf8, 0x3d, 0x8d, 0x34, 0xa3, 0x4b, 0x7b, 0xa2, 0xae, 0x13, 0x84, 0xd7,
	0x05, 0xda, 0x06, 0xe1, 0x05, 0xa1, 0xf1, 0x0d, 0x4f, 0xdf, 0xde, 0x56, 0x6d, 0x22, 0x8d, 0xa7,
	0xac, 0xf5, 0x35, 0x8b, 0xac, 0xbc, 0x85, 0xf2, 0xe4, 0x3f, 0x66, 0xe7, 0xba, 0xe6, 0xbc, 0x4c,
	0x09, 0xe3, 0xda, 0x5d, 0xe7, 0x68, 0x28, 0xc1, 0x64, 0x4e, 0x95, 0x26, 0xd4, 0xa3, 0x43, 0x68,
	0xf5, 0xe2, 0xb8, 0x9f, 0x39, 0xa5, 0x52, 0x72, 0xda, 0x19, 0xf1, 0xac, 0xea, 0x04, 0x80, 0xbe,
	0x9b, 0x65, 0x7a, 0x89, 0x6f, 0xdd, 0x95, 0x99, 0x4c, 0xca, 0xc5, 0xb4, 0xfb, 0xad, 0x82, 0x79,
	0xf7, 0x45, 0x4c, 0x51, 0x7b, 0xdf, 0xe3, 0xbd, 0x49, 0x3e, 0x37, 0x7f, 0x04, 0xce, 0x49, 0x44,
	0xbf, 0xb1, 0xc6, 0xb5, 0x9f, 0x5a, 0xce, 0xe7, 0x96, 0xe2, 0x65, 0x96, 0x50, 0xc1, 0x82, 0x6e,
	0x17, 0x30, 0x1f, 0x69, 0xc7, 0x3a, 0xe8, 0x68, 0xc0, 0xca, 0xce, 0xea, 0xde, 0xae, 0x4a, 0x1c,
	0xda, 0x02, 0x50, 0x75, 0x18, 0x9e, 0x43, 0x9d, 0x98, 0x81, 0xcc, 0x08, 0x98, 0xb8, 0x5a, 0x60,
	0x24, 0x41, 0x5b, 0x65, 0x8e, 0x77, 0xf1, 0xb4, 0x32, 0x7f, 0x44, 0x4a, 0x53, 0x49, 0x71, 0x4a,
	0x61, 0xb9, 0x8d, 0xda, 0x41, 0x7a, 0xd4, 0x39, 0x82, 0x65, 0x64, 0xcb, 0xb7, 0x27, 0xda, 0x09,
	0xbd, 0x2e, 0x7a, 0x8a, 0x61, 0x09, 0x3d, 0x6d, 0x08, 0x61, 0x38, 0xc5, 0x96, 0x84, 0x7f, 0xd3,
	0xba, 0x7a, 0xdd, 0xc2, 0x7b, 0x71, 0x49, 0x3d, 0xe4, 0xe4, 0x0d, 0x9a, 0x7b, 0xda, 0x99, 0x6b,
	0xd0, 0xd3, 0x71, 0xed, 0x1d, 0xe7, 0xed, 0x24, 0x0e, 0xc3, 0x19, 0x7b, 0x62, 0x97, 0x4a, 0x27,
	0xea, 0x8d, 0xca, 0x54, 0x52, 0xea, 0x34, 0xdf, 0xa2, 0x3e, 0x8b, 0xa3, 0x2d, 0xa9, 0xa5, 0x79,
	0x2f, 0x93, 0xa1, 0xe3, 0xc9, 0x80, 0xd6, 0xa8, 0xb5, 0xea, 0x2a, 0x7f, 0xb8, 0x32, 0x49, 0xa2,
	0x58, 0xb4, 0xf0, 0x7f, 0x59, 0x64, 0xfd, 0x0d, 0x08, 0x41, 0xc0, 0xd3, 0xe1, 0xbe, 0x2b, 0x6f,
	0x24, 0x6d, 0x29, 0x21, 0xc3, 0xaa, 0x8e, 0x19, 0xc4, 0x97, 0xc1, 0xcd, 0x82, 0x7b, 0xba, 0xbe,
	0x50, 0x79, 0xfb, 0x6a, 0x06, 0xc9, 0xfe, 0xd8, 0x22, 0x1b, 0x47, 0x01, 0x17, 0xb8, 0x37, 0x48,
	0xb7, 0x9b, 0x7f, 0x2c, 0xaf, 0xe5, 0x81, 0x72, 0xf7, 0x68, 0x5c, 0x7b, 0xd5, 0xf9, 0x9b, 0x30,
	0xe0, 0x42, 0x6b, 0xaf, 0xef, 0x93, 0x98, 0x5e, 0xe5, 0x7b, 0x10, 0xee, 0xdc, 0x02, 0x04, 0x98,
	0x48, 0xe9, 0xfa, 0x25, 0xc8, 0x8b, 0xba, 0xc0, 0xf3, 0x07, 0x88, 0x04, 0xf2, 0x89, 0x45, 0xc8,
	0xed, 0x20, 0x6a, 0xbf, 0x05, 0xac, 0x0f, 0xec, 0x1c, 0xa7, 0x9f, 0xfb, 0xc7, 0x89, 0xfb, 0xe6,
	0xb8, 0xf6, 0xb2, 0xb3, 0x83, 0xc7, 0x6f, 0x04, 0x62, 0x18, 0xb3, 0x3e, 0x0d, 0x63, 0x5f, 0x95,
	0x82, 0x71, 0x87, 0x0e, 0xa5, 0x40, 0x85, 0x28, 0xe0, 0xd4, 0x4f, 0x19, 0x63, 0x10, 0x89, 0x70,
	0x44, 0xf3, 0xb5, 0xa1, 0x9a, 0xb5, 0x1d, 0xc6, 0xfe, 0x2d, 0x36, 0xae, 0xf5, 0xed, 0x1a, 0xb9,
	0x28, 0x1f, 0xce, 0xa8, 0x7a, 0x39, 0xa3, 0x4d, 0x60, 0xa7, 0xc0, 0xdc, 0x17, 0x48, 0xf9, 0x5d,
	0xe0, 0x3c, 0xa0, 0xbc, 0xe7, 0x45, 0x7d, 0xe7, 0xb2, 0x6c, 0xc8, 0xef, 0xbf, 0x0f, 0xe1, 0x14,
	0xc2, 0x1b, 0x37, 0xaa, 0x7e, 0x3c, 0xd8, 0x59, 0xb8, 0x51, 0xbd, 0x7e, 0xb5, 0x60, 0x15, 0x76,
	0x2a, 0x1e, 0x66, 0x54, 0x05, 0x66, 0xfb, 0x5d, 0x1e, 0x47, 0x37, 0xcf, 0xf4, 0xfc, 0x53, 0x21,
	0x69, 0xb5, 0x8a, 0x92, 0xea, 0xbf, 0xfe, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x9e, 0xf3,
	0x84, 0x94, 0x20, 0x00, 0x00,
}
