name: CI 

on:
  push:
    branches:
      - staging
      - trying
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cargo_checks:
          - name: Enforce default cargo fmt
            subcommand: fmt -- --check
          - name: Clippy
            subcommand: clippy
          - name: Test
            subcommand: test --verbose
          - name: Build
            subcommand: build --release --all-features --verbose
    steps:
    - uses: actions/checkout@v2
    - name: Stable with rustfmt and clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v1
    - name: cargo check - ${{ matrix.cargo_checks.name }} 
      run: cargo ${{ matrix.cargo_checks.subcommand }}
  done:
    name: Done
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo "Done!"